

-------------------------------------------------------------------------------
--  notification message
-------------------------------------------------------------------------------
CREATE TABLE NOTIFICATION_MESSAGE(
    ID BIGINT AUTO_INCREMENT,
    REQUEST_KEY VARCHAR(50),
    DESTINATION VARCHAR(200),
    TEMPLATE_CODE VARCHAR(50),
    CONTENT TEXT,
    CATALOG VARCHAR(50),
    SOURCE VARCHAR(50),
    TAG VARCHAR(50),

    PRIORITY INT,
    CREATE_TIME TIMESTAMP,
    UPDATE_TIME TIMESTAMP,
    STATUS VARCHAR(50),

    APP VARCHAR(50),

    CONFIG_ID BIGINT,
    QUEUE_ID BIGINT,

    CONSTRAINT PK_NOTIFICATION_MESSAGE PRIMARY KEY(ID),
    CONSTRAINT FK_NOTIFICATION_MESSAGE_CONFIG FOREIGN KEY (CONFIG_ID) REFERENCES NOTIFICATION_CONFIG(ID),
    CONSTRAINT FK_NOTIFICATION_MESSAGE_QUEUE FOREIGN KEY (QUEUE_ID) REFERENCES NOTIFICATION_QUEUE(ID)
) ENGINE=INNODB CHARSET=UTF8;




















