

-------------------------------------------------------------------------------
--  GLOBAL
-------------------------------------------------------------------------------
CREATE TABLE SCOPE_GLOBAL(
        ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
        NAME VARCHAR(50),
	REFERENCE VARCHAR(50),
        CONSTRAINT PK_SCOPE_GLOBAL PRIMARY KEY(ID)
);

