

ALTER TABLE OPEN_APP ADD COLUMN LOGO VARCHAR(200);
ALTER TABLE OPEN_APP ADD COLUMN USERGUIDE VARCHAR(200);
ALTER TABLE OPEN_APP ADD COLUMN ADMIN_URL VARCHAR(200);
ALTER TABLE OPEN_APP ADD COLUMN LANGUAGE VARCHAR(100);
ALTER TABLE OPEN_APP ADD COLUMN VERSION_NO VARCHAR(10);
ALTER TABLE OPEN_APP ADD COLUMN DEVELOPER_NAME VARCHAR(50);
ALTER TABLE OPEN_APP ADD COLUMN DEVELOPER_USER_ID VARCHAR(50);
ALTER TABLE OPEN_APP ADD COLUMN CATEGORY VARCHAR(50);










