

ALTER TABLE SYS_INFO ADD COLUMN APP_KEY VARCHAR(200);
ALTER TABLE SYS_INFO ADD COLUMN APP_SECRET VARCHAR(200);
ALTER TABLE SYS_INFO ADD COLUMN APP_URL VARCHAR(200);
ALTER TABLE SYS_INFO ADD COLUMN PC_URL VARCHAR(200);
ALTER TABLE SYS_INFO ADD COLUMN ADMIN_URL VARCHAR(200);







