
CREATE TABLE BPM_TASK_CONF(
	ID BIGINT AUTO_INCREMENT,
	BUSINESS_KEY VARCHAR(200),
	TASK_DEFINITION_KEY VARCHAR(200),
	ASSIGNEE VARCHAR(200),
        CONSTRAINT PK_BPM_TASK_CONF PRIMARY KEY(ID)
) ENGINE=INNODB CHARSET=UTF8;

