
CREATE TABLE BPM_DELEGATE_INFO(
	ID BIGINT AUTO_INCREMENT,
	ASSIGNEE VARCHAR(200),
	ATTORNEY VARCHAR(200),
	START_TIME TIMESTAMP,
	END_TIME TIMESTAMP,
	PROCESS_DEFINITION_ID VARCHAR(100),
	STATUS INTEGER,
        CONSTRAINT PK_BPM_DELEGATE_INFO PRIMARY KEY(ID)
) ENGINE=INNODB CHARSET=UTF8;
