
CREATE TABLE BPM_CONF_NOTICE(
	ID BIGINT NOT NULL,
	TYPE INT,
	RECEIVER VARCHAR(200),
	DUE_DATE VARCHAR(50),
	NODE_ID BIGINT,
	TEMPLATE_ID BIGINT,
        CONSTRAINT PK_BPM_CONF_NOTICE PRIMARY KEY(ID),
        CONSTRAINT FK_BPM_CONF_NOTICE_NODE FOREIGN KEY(NODE_ID) REFERENCES BPM_CONF_NODE(ID),
        CONSTRAINT FK_BPM_CONF_NOTICE_TEMPLATE FOREIGN KEY(TEMPLATE_ID) REFERENCES BPM_MAIL_TEMPLATE(ID)
) ENGINE=INNODB CHARSET=UTF8;









