
CREATE TABLE BPM_CONF_OPERATION(
	ID BIGINT AUTO_INCREMENT,
	VALUE VARCHAR(200),
	PRIORITY INT,
	NODE_ID BIGINT,
        CONSTRAINT PK_BPM_CONF_OPERATION PRIMARY KEY(ID),
        CONSTRAINT FK_BPM_CONF_OPERATION_NODE FOREIGN KEY(NODE_ID) REFERENCES BPM_CONF_NODE(ID)
) ENGINE=INNODB CHARSET=UTF8;

