
CREATE TABLE BPM_CONF_BASE(
	ID BIGINT NOT NULL,
	PROCESS_DEFINITION_ID VARCHAR(200),
	PROCESS_DEFINITION_KEY VARCHAR(200),
	PROCESS_DEFINITION_VERSION INT,
        CONSTRAINT PK_BPM_CONF_BASE PRIMARY KEY(ID)
) ENGINE=INNODB CHARSET=UTF8;







