
ALTER TABLE BPM_PROCESS ADD COLUMN CODE VARCHAR(64);
ALTER TABLE BPM_PROCESS ADD COLUMN CONF_BASE_ID BIGINT;

ALTER TABLE BPM_PROCESS ADD CONSTRAINT FK_BPM_PROCESS_CONF_BASE FOREIGN KEY(CONF_BASE_ID) REFERENCES BPM_CONF_BASE(ID);

ALTER TABLE BPM_PROCESS DROP COLUMN PROCESS_DEFINITION_KEY;
ALTER TABLE BPM_PROCESS DROP COLUMN PROCESS_DEFINITION_VERSION;



