
CREATE TABLE BPM_CONF_FORM(
	ID BIGINT NOT NULL,
	VALUE VARCHAR(200),
	TYPE INT,
	ORIGIN_VALUE VARCHAR(200),
	ORIGIN_TYPE INT,
	STATUS INT,
	NODE_ID BIGINT,
        CONSTRAINT PK_BPM_CONF_FORM PRIMARY KEY(ID),
        CONSTRAINT FK_BPM_CONF_FORM_NODE FOREIGN KEY(NODE_ID) REFERENCES BPM_CONF_NODE(ID)
) ENGINE=INNODB CHARSET=UTF8;










