
CREATE TABLE BPM_INSTANCE(
	ID BIGINT NOT NULL,
	NAME VARCHAR(200),
	BUSINESS_KEY VARCHAR(64),
	REF VARCHAR(64),
	CREATE_TIME DATETIME,
	INITIATOR VARCHAR(64),
	PRIORITY INTEGER,
	TENANT_ID VARCHAR(64),
	PROCESS_ID BIGINT,
        CONSTRAINT PK_BPM_INSTANCE PRIMARY KEY(ID),
        CONSTRAINT FK_BPM_INSTANCE_PROCESS FOREIGN KEY(PROCESS_ID) REFERENCES BPM_PROCESS(ID)
) ENGINE=INNODB CHARSET=UTF8;












