
CREATE TABLE BPM_SEQUENCE(
	ID BIGINT NOT NULL,
	CODE VARCHAR(100),
	SOURCE_CODE VARCHAR(100),
	TARGET_CODE VARCHAR(100),
	CREATE_TIME DATETIME,
	PROCESS_INSTANCE_ID VARCHAR(100),
	TYPE VARCHAR(50),

	TENANT_ID VARCHAR(64),
        CONSTRAINT PK_BPM_SEQUENCE PRIMARY KEY(ID)
) ENGINE=INNODB CHARSET=UTF8;


