
INSERT INTO PLM_CONFIG(ID,CODE,NAME) VALUES(1,'default','默认配置');

INSERT INTO PLM_STEP(ID,CODE,NAME,ACTION,PRIORITY,CONFIG_ID) VALUES(1,'request','需求池','none',1,1);
INSERT INTO PLM_STEP(ID,CODE,NAME,ACTION,PRIORITY,CONFIG_ID) VALUES(2,'preDev','准备开发','none',2,1);
INSERT INTO PLM_STEP(ID,CODE,NAME,ACTION,PRIORITY,CONFIG_ID) VALUES(3,'dev','开发中','start',3,1);
INSERT INTO PLM_STEP(ID,CODE,NAME,ACTION,PRIORITY,CONFIG_ID) VALUES(4,'preTest','准备测试','stop',4,1);
INSERT INTO PLM_STEP(ID,CODE,NAME,ACTION,PRIORITY,CONFIG_ID) VALUES(5,'test','测试中','start',5,1);
INSERT INTO PLM_STEP(ID,CODE,NAME,ACTION,PRIORITY,CONFIG_ID) VALUES(6,'preConfirm','准备验证','stop',6,1);
INSERT INTO PLM_STEP(ID,CODE,NAME,ACTION,PRIORITY,CONFIG_ID) VALUES(7,'confirm','验证完成','complete',7,1);

INSERT INTO PLM_SPRINT(ID,NAME,START_TIME,END_TIME,STATUS,PROJECT_ID,CONFIG_ID) VALUES(1,'global-1.0.0.0','2015-01-01 00:00:00','2015-01-31 00:00:00','active',11,1);

