

INSERT INTO BPM_CATEGORY(ID,NAME,PRIORITY) VALUES(1,'常用流程',1);

INSERT INTO BPM_PROCESS(ID,NAME,PRIORITY,DESCN,CATEGORY_ID,PROCESS_DEFINITION_KEY,PROCESS_DEFINITION_VERSION,USE_TASK_CONF) VALUES(1,'请假流程',1,'通用请假流程',1,'vacation',1,0);

INSERT INTO BPM_PROCESS(ID,NAME,PRIORITY,DESCN,CATEGORY_ID,PROCESS_DEFINITION_KEY,PROCESS_DEFINITION_VERSION,USE_TASK_CONF) VALUES(2,'发文流程',2,'通用发文流程',1,'publish',1,0);

INSERT INTO BPM_PROCESS(ID,NAME,PRIORITY,DESCN,CATEGORY_ID,PROCESS_DEFINITION_KEY,PROCESS_DEFINITION_VERSION,USE_TASK_CONF) VALUES(3,'权限审批',3,'权限审批流程',1,'permission',1,1);

INSERT INTO BPM_TASK_DEF_NOTICE(ID,TASK_DEFINITION_KEY,TYPE,RECEIVER,TEMPLATE,DUE_DATE,PROCESS_ID) VALUES(1,'taskuser-2',0,'任务接收人','#{task.assignee}您好，您有新任务需要处理——#{task.name}。',NULL,1);

INSERT INTO BPM_TASK_DEF_NOTICE(ID,TASK_DEFINITION_KEY,TYPE,RECEIVER,TEMPLATE,DUE_DATE,PROCESS_ID) VALUES(2,'taskuser-3',0,'流程发起人','#{initiator}您好，您的流程已经到达#{task.name}环节',NULL,1);

INSERT INTO BPM_TASK_DEF_NOTICE(ID,TASK_DEFINITION_KEY,TYPE,RECEIVER,TEMPLATE,DUE_DATE,PROCESS_ID) VALUES(3,'taskuser-6',1,'king','您好，#{initiator}的流程已经完成#{task.name}环节',NULL,1);

INSERT INTO BPM_TASK_DEF_NOTICE(ID,TASK_DEFINITION_KEY,TYPE,RECEIVER,TEMPLATE,DUE_DATE,PROCESS_ID) VALUES(4,'taskuser-6',2,'流程发起人','#{task.assignee}您好，任务#{task.name}已经即将到期','P1H',1);

