

INSERT INTO BPM_CATEGORY(ID,NAME,PRIORITY) VALUES(1,'常用流程',1);

INSERT INTO BPM_PROCESS(ID,NAME,PRIORITY,DESCN,CATEGORY_ID,PROCESS_DEFINITION_KEY,PROCESS_DEFINITION_VERSION,USE_TASK_CONF) VALUES(1,'请假流程',1,'通用请假流程',1,'vacation',1,0);

INSERT INTO BPM_PROCESS(ID,NAME,PRIORITY,DESCN,CATEGORY_ID,PROCESS_DEFINITION_KEY,PROCESS_DEFINITION_VERSION,USE_TASK_CONF) VALUES(2,'发文流程',2,'通用发文流程',1,'publish',1,0);

INSERT INTO BPM_PROCESS(ID,NAME,PRIORITY,DESCN,CATEGORY_ID,PROCESS_DEFINITION_KEY,PROCESS_DEFINITION_VERSION,USE_TASK_CONF) VALUES(3,'权限审批',3,'权限审批流程',1,'permission',1,1);


