

-------------------------------------------------------------------------------
--  audit extra
-------------------------------------------------------------------------------
CREATE TABLE AUDIT_EXTRA(
        ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
        NAME VARCHAR(200),
	VALUE VARCHAR(200),
	AUDIT_BASE_ID BIGINT,
        CONSTRAINT PK_AUDIT_EXTRA PRIMARY KEY(ID)
);

