

INSERT INTO TICKET_CATALOG(ID,NAME) VALUES(1,'默认分类');

INSERT INTO TICKET_GROUP(ID,NAME) VALUES(1,'默认组');

INSERT INTO TICKET_INFO(ID,CODE,NAME,CREATOR,CREATE_TIME,STATUS,CATALOG_ID,GROUP_ID) VALUES(1,'1','测试','1','2015-03-05 00:00:00','new',1,1);

INSERT INTO TICKET_MEMBER(ID,USER,GROUP_ID) VALUES(1,'1',1);

