

UPDATE AUTH_MENU SET URL='/report/index.do' WHERE ID=16;
UPDATE AUTH_MENU SET CODE='system' WHERE ID=81;
UPDATE AUTH_MENU SET URL='/pim/index.do' WHERE ID=13;

INSERT INTO AUTH_PERM_ROLE_DEF(PERM_ID,ROLE_DEF_ID) VALUES(201,9);
INSERT INTO AUTH_PERM_ROLE_DEF(PERM_ID,ROLE_DEF_ID) VALUES(201,10);
INSERT INTO AUTH_PERM_ROLE_DEF(PERM_ID,ROLE_DEF_ID) VALUES(201,11);

INSERT INTO AUTH_PERM(ID,CODE,NAME,PERM_TYPE_ID,TENANT_ID) VALUES(503,'feedback','反馈管理',51,'1');
INSERT INTO AUTH_MENU(ID,TYPE,CODE,TITLE,URL,PRIORITY,PARENT_ID,PERM_ID,DISPLAY) VALUES(503,'module','feedback','反馈管理','/feedback/feedback-info-list.do',503,51,503,'true');
INSERT INTO AUTH_PERM_ROLE_DEF(PERM_ID,ROLE_DEF_ID) VALUES(503,5);


UPDATE AUTH_MENU SET DISPLAY='true' where ID=91;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=101;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=111;

UPDATE AUTH_MENU SET DISPLAY='true' where ID=604;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=605;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=606;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=607;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=608;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=609;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=610;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=611;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=612;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=613;

UPDATE AUTH_MENU SET DISPLAY='true' where ID=705;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=706;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=707;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=708;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=709;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=710;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=711;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=712;
UPDATE AUTH_MENU SET DISPLAY='true' where ID=713;

UPDATE AUTH_MENU SET PRIORITY=40000 WHERE ID=31;
UPDATE AUTH_MENU SET PRIORITY=50000 WHERE ID=41;
UPDATE AUTH_MENU SET PRIORITY=60000 WHERE ID=51;
UPDATE AUTH_MENU SET PRIORITY=70000 WHERE ID=61;
UPDATE AUTH_MENU SET PRIORITY=80000 WHERE ID=71;
UPDATE AUTH_MENU SET PRIORITY=90000 WHERE ID=91;
UPDATE AUTH_MENU SET PRIORITY=100000 WHERE ID=101;
UPDATE AUTH_MENU SET PRIORITY=110000 WHERE ID=111;
UPDATE AUTH_MENU SET PRIORITY=990000 WHERE ID=81;

