

INSERT INTO DICT_INFO(ID,NAME,STRING_VALUE,LONG_VALUE,DOUBLE_VALUE) VALUES(1,'UIC_EMAILGROUP_VERSION',NULL,0,NULL);
INSERT INTO DICT_INFO(ID,NAME,STRING_VALUE,LONG_VALUE,DOUBLE_VALUE) VALUES(2,'UIC_DEPARTMENT_VERSION',NULL,0,NULL);
INSERT INTO DICT_INFO(ID,NAME,STRING_VALUE,LONG_VALUE,DOUBLE_VALUE) VALUES(3,'UIC_USER_VERSION',NULL,0,NULL);

