

ALTER TABLE PIM_INFO ADD COLUMN USER_ID VARCHAR(64);
ALTER TABLE PIM_INFO ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;
ALTER TABLE PIM_SCHEDULE ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE PIM_SCHEDULE_PARTICIPANT ADD COLUMN TENANT_ID VARCHAR(64);

