

ALTER TABLE PIM_INFO ADD COLUMN DEPARTMENT VARCHAR(100);
ALTER TABLE PIM_INFO ADD COLUMN IMPP VARCHAR(100);
ALTER TABLE PIM_INFO ADD COLUMN TYPE VARCHAR(50);
ALTER TABLE PIM_INFO ADD COLUMN REF VARCHAR(64);

