

-------------------------------------------------------------------------------
--  pim remind
-------------------------------------------------------------------------------
CREATE TABLE PIM_REMIND(
        ID BIGINT NOT NULL,
	TYPE VARCHAR(50),
	REPEAT_TYPE VARCHAR(64),
	REPEAT_PEROID INT,
	PRIORITY INT,
	REMIND_TIME VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	CREATE_TIME DATETIME,
	STATUS VARCHAR(50),
	USER_ID VARCHAR(64),
	REF VARCHAR(200),
        CONSTRAINT PK_PIM_REMIND PRIMARY KEY(ID)
);

COMMENT ON TABLE PIM_REMIND IS '提醒';
COMMENT ON COLUMN PIM_REMIND.ID IS '主键';
COMMENT ON COLUMN PIM_REMIND.TYPE IS '重复类型，一次，每天，每周';
COMMENT ON COLUMN PIM_REMIND.REPEAT_TYPE IS '是否重复提醒';
COMMENT ON COLUMN PIM_REMIND.REPEAT_PEROID IS '提醒间隔';
COMMENT ON COLUMN PIM_REMIND.PRIORITY IS '优先级';
COMMENT ON COLUMN PIM_REMIND.REMIND_TIME IS '提醒时间';
COMMENT ON COLUMN PIM_REMIND.DESCRIPTION IS '备注';
COMMENT ON COLUMN PIM_REMIND.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN PIM_REMIND.STATUS IS '状态';
COMMENT ON COLUMN PIM_REMIND.USER_ID IS '用户';
COMMENT ON COLUMN PIM_REMIND.REF IS '外部引用';

