

ALTER TABLE CMS_COMMENT ADD COLUMN IP VARCHAR(50);
ALTER TABLE CMS_COMMENT ADD COLUMN PRIORITY INT;
ALTER TABLE CMS_COMMENT ADD COLUMN CONVERSATION BIGINT;
ALTER TABLE CMS_COMMENT ADD COLUMN TYPE VARCHAR(50);

ALTER TABLE CMS_CATALOG ADD COLUMN PRIORITY INT;
ALTER TABLE CMS_CATALOG ADD COLUMN STATUS VARCHAR(50);

