

ALTER TABLE SENDMAIL_CONFIG ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;
ALTER TABLE SENDMAIL_TEMPLATE ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;
ALTER TABLE SENDMAIL_ATTACHMENT ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;
ALTER TABLE SENDMAIL_QUEUE ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;
ALTER TABLE SENDMAIL_HISTORY ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;

