
ALTER TABLE CMS_SITE ADD COLUMN STATUS VARCHAR(50);
ALTER TABLE CMS_SITE ADD COLUMN DOMAIN VARCHAR(200);
ALTER TABLE CMS_SITE ADD COLUMN WATERMARK_TYPE VARCHAR(50);
ALTER TABLE CMS_SITE ADD COLUMN WATERMARK_TEXT VARCHAR(200);
ALTER TABLE CMS_SITE ADD COLUMN TEMPLATE_TAG VARCHAR(100);

