

-------------------------------------------------------------------------------
--  plm requirement
-------------------------------------------------------------------------------
CREATE TABLE PLM_REQUIREMENT(
    ID BIGINT NOT NULL,
    NAME VARCHAR(200),
    CATEGORY VARCHAR(50),
    SEVERITY VARCHAR(50),
    PRIORITY INT,
    TYPE VARCHAR(50),
    DEADLINE DATE,
    DESCRIPTION VARCHAR(200),
    TAG VARCHAR(200),
    STATUS VARCHAR(50),
    CREATE_TIME DATETIME,
    USER_ID VARCHAR(64),
    PARENT_ID BIGINT,
    ISSUE_ID BIGINT,
    VERSION_ID BIGINT,
    PROJECT_ID BIGINT,
    GROUP_NAME VARCHAR(200),
    ASSIGNEE VARCHAR(64),
    CONSTRAINT PK_PLM_REQUIREMENT PRIMARY KEY(ID),
    CONSTRAINT FK_PIM_REQUIREMENT_PARENT FOREIGN KEY(PARENT_ID) REFERENCES PLM_REQUIREMENT(ID),
    CONSTRAINT FK_PIM_REQUIREMENT_ISSUE FOREIGN KEY(ISSUE_ID) REFERENCES PLM_ISSUE(ID),
    CONSTRAINT FK_PIM_REQUIREMENT_VERSION FOREIGN KEY(VERSION_ID) REFERENCES PLM_VERSION(ID),
    CONSTRAINT FK_PIM_REQUIREMENT_PROJECT FOREIGN KEY(PROJECT_ID) REFERENCES PLM_PROJECT(ID)
);

COMMENT ON TABLE PLM_REQUIREMENT IS '需求';
COMMENT ON COLUMN PLM_REQUIREMENT.ID IS '主键';
COMMENT ON COLUMN PLM_REQUIREMENT.NAME IS '标题';
COMMENT ON COLUMN PLM_REQUIREMENT.CATEGORY IS '分类：新功能，功能优化，线上bug，运营需求，问题反馈';
COMMENT ON COLUMN PLM_REQUIREMENT.SEVERITY IS '紧急程度';
COMMENT ON COLUMN PLM_REQUIREMENT.PRIORITY IS '优先级';
COMMENT ON COLUMN PLM_REQUIREMENT.TYPE IS '需求类型：产品，业务，技术，其他';
COMMENT ON COLUMN PLM_REQUIREMENT.DEADLINE IS '截止时间';
COMMENT ON COLUMN PLM_REQUIREMENT.DESCRIPTION IS '备注';
COMMENT ON COLUMN PLM_REQUIREMENT.USER_ID IS '创建人';
COMMENT ON COLUMN PLM_REQUIREMENT.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN PLM_REQUIREMENT.PROJECT_ID IS '所属项目';
COMMENT ON COLUMN PLM_REQUIREMENT.GROUP_NAME IS '负责团队';
COMMENT ON COLUMN PLM_REQUIREMENT.ASSIGNEE IS '负责人';

