package com.mossle.party.domain;

// Generated by Hibernate Tools
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PartyStructRuleId .
 * 
 * @author Lingo
 */
@Embeddable
public class PartyStructRuleId implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** . */
    private long structTypeId;

    /** . */
    private long parentTypeId;

    /** . */
    private long childTypeId;

    public PartyStructRuleId() {
    }

    public PartyStructRuleId(long structTypeId, long parentTypeId,
            long childTypeId) {
        this.structTypeId = structTypeId;
        this.parentTypeId = parentTypeId;
        this.childTypeId = childTypeId;
    }

    /** @return . */
    @Column(name = "STRUCT_TYPE_ID", nullable = false)
    public long getStructTypeId() {
        return this.structTypeId;
    }

    /**
     * @param structTypeId
     *            .
     */
    public void setStructTypeId(long structTypeId) {
        this.structTypeId = structTypeId;
    }

    /** @return . */
    @Column(name = "PARENT_TYPE_ID", nullable = false)
    public long getParentTypeId() {
        return this.parentTypeId;
    }

    /**
     * @param parentTypeId
     *            .
     */
    public void setParentTypeId(long parentTypeId) {
        this.parentTypeId = parentTypeId;
    }

    /** @return . */
    @Column(name = "CHILD_TYPE_ID", nullable = false)
    public long getChildTypeId() {
        return this.childTypeId;
    }

    /**
     * @param childTypeId
     *            .
     */
    public void setChildTypeId(long childTypeId) {
        this.childTypeId = childTypeId;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof PartyStructRuleId)) {
            return false;
        }

        PartyStructRuleId castOther = (PartyStructRuleId) other;

        return (this.getStructTypeId() == castOther.getStructTypeId())
                && (this.getParentTypeId() == castOther.getParentTypeId())
                && (this.getChildTypeId() == castOther.getChildTypeId());
    }

    public int hashCode() {
        int result = 17;

        result = (37 * result) + (int) this.getStructTypeId();
        result = (37 * result) + (int) this.getParentTypeId();
        result = (37 * result) + (int) this.getChildTypeId();

        return result;
    }
}
