package com.mossle.notification.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NotificationConfig 通知配置.
 * 
 * @author Lingo
 */
@Entity
@Table(name = "NOTIFICATION_CONFIG")
public class NotificationConfig implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** id. */
    private Long id;

    /** 分类. */
    private NotificationCatalog notificationCatalog;

    /** 编码. */
    private String code;

    /** 名称. */
    private String name;

    /** 内容. */
    private String content;

    /** 优先级. */
    private Integer priority;

    /** 创建时间. */
    private Date createTime;

    /** 创建人. */
    private String creator;

    /** 更新时间. */
    private Date updateTime;

    /** 更新人. */
    private String updater;

    /** 状态. */
    private String status;

    /** APP. */
    private String app;

    /** . */
    private Set<NotificationMessage> notificationMessages = new HashSet<NotificationMessage>(
            0);

    /** . */
    private Set<NotificationQueue> notificationQueues = new HashSet<NotificationQueue>(
            0);

    public NotificationConfig() {
    }

    public NotificationConfig(Long id) {
        this.id = id;
    }

    public NotificationConfig(Long id, NotificationCatalog notificationCatalog,
            String code, String name, String content, Integer priority,
            Date createTime, String creator, Date updateTime, String updater,
            String status, String app,
            Set<NotificationMessage> notificationMessages,
            Set<NotificationQueue> notificationQueues) {
        this.id = id;
        this.notificationCatalog = notificationCatalog;
        this.code = code;
        this.name = name;
        this.content = content;
        this.priority = priority;
        this.createTime = createTime;
        this.creator = creator;
        this.updateTime = updateTime;
        this.updater = updater;
        this.status = status;
        this.app = app;
        this.notificationMessages = notificationMessages;
        this.notificationQueues = notificationQueues;
    }

    /** @return id. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            id.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return 分类. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CATALOG_ID")
    public NotificationCatalog getNotificationCatalog() {
        return this.notificationCatalog;
    }

    /**
     * @param notificationCatalog
     *            分类.
     */
    public void setNotificationCatalog(NotificationCatalog notificationCatalog) {
        this.notificationCatalog = notificationCatalog;
    }

    /** @return 编码. */
    @Column(name = "CODE", length = 50)
    public String getCode() {
        return this.code;
    }

    /**
     * @param code
     *            编码.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /** @return 名称. */
    @Column(name = "NAME", length = 50)
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            名称.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** @return 内容. */
    @Column(name = "CONTENT", length = 65535)
    public String getContent() {
        return this.content;
    }

    /**
     * @param content
     *            内容.
     */
    public void setContent(String content) {
        this.content = content;
    }

    /** @return 优先级. */
    @Column(name = "PRIORITY")
    public Integer getPriority() {
        return this.priority;
    }

    /**
     * @param priority
     *            优先级.
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /** @return 创建时间. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_TIME", length = 26)
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * @param createTime
     *            创建时间.
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /** @return 创建人. */
    @Column(name = "CREATOR", length = 64)
    public String getCreator() {
        return this.creator;
    }

    /**
     * @param creator
     *            创建人.
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /** @return 更新时间. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_TIME", length = 26)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    /**
     * @param updateTime
     *            更新时间.
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /** @return 更新人. */
    @Column(name = "UPDATER", length = 64)
    public String getUpdater() {
        return this.updater;
    }

    /**
     * @param updater
     *            更新人.
     */
    public void setUpdater(String updater) {
        this.updater = updater;
    }

    /** @return 状态. */
    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    /**
     * @param status
     *            状态.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /** @return APP. */
    @Column(name = "APP", length = 50)
    public String getApp() {
        return this.app;
    }

    /**
     * @param app
     *            APP.
     */
    public void setApp(String app) {
        this.app = app;
    }

    /** @return . */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "notificationConfig")
    public Set<NotificationMessage> getNotificationMessages() {
        return this.notificationMessages;
    }

    /**
     * @param notificationMessages
     *            .
     */
    public void setNotificationMessages(
            Set<NotificationMessage> notificationMessages) {
        this.notificationMessages = notificationMessages;
    }

    /** @return . */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "notificationConfig")
    public Set<NotificationQueue> getNotificationQueues() {
        return this.notificationQueues;
    }

    /**
     * @param notificationQueues
     *            .
     */
    public void setNotificationQueues(Set<NotificationQueue> notificationQueues) {
        this.notificationQueues = notificationQueues;
    }
}
