

-------------------------------------------------------------------------------
--  disk info
-------------------------------------------------------------------------------
CREATE TABLE DISK_INFO(
    ID BIGINT NOT NULL,
	NAME VARCHAR(200),
	DESCRIPTION VARCHAR(255),
	TYPE VARCHAR(50),
	FILE_SIZE BIGINT,
	CREATOR VARCHAR(64),
	CREATE_TIME DATETIME,
	REF VARCHAR(200),
	PREVIEW_STATUS VARCHAR(50),
	PREVIEW_REF VARCHAR(200),
	PARENT_ID BIGINT,
	PARENT_PATH VARCHAR(200),
	DIR_TYPE INT,
	PRIORITY INT,

	LAST_MODIFIER VARCHAR(64),
	LAST_MODIFIED_TIME DATETIME,
	STATUS VARCHAR(50),
	EXPIRE_TIME DATETIME,
	CHECKOUT_STATUS VARCHAR(50),
	FILE_VERSION VARCHAR(50),
	SECURITY_LEVEL VARCHAR(50),
    CONSTRAINT PK_DISK_INFO PRIMARY KEY(ID),
	CONSTRAINT FK_DISK_INFO_PARENT FOREIGN KEY (PARENT_ID) REFERENCES DISK_INFO(ID)
);

CREATE INDEX IDX_DISK_INFO_NAME ON DISK_INFO(NAME);

COMMENT ON TABLE DISK_INFO IS '文件信息';
COMMENT ON COLUMN DISK_INFO.ID IS '主键';
COMMENT ON COLUMN DISK_INFO.NAME IS '名称';
COMMENT ON COLUMN DISK_INFO.DESCRIPTION IS '备注';
COMMENT ON COLUMN DISK_INFO.TYPE IS '类型';
COMMENT ON COLUMN DISK_INFO.FILE_SIZE IS '文件大小';
COMMENT ON COLUMN DISK_INFO.CREATOR IS '创建人';
COMMENT ON COLUMN DISK_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN DISK_INFO.REF IS '外部引用';
COMMENT ON COLUMN DISK_INFO.PREVIEW_STATUS IS '预览状态';
COMMENT ON COLUMN DISK_INFO.PREVIEW_REF IS '预览引用';
COMMENT ON COLUMN DISK_INFO.PARENT_ID IS '上级文件';
COMMENT ON COLUMN DISK_INFO.PARENT_PATH IS '上级路径';
COMMENT ON COLUMN DISK_INFO.DIR_TYPE IS '是否目录';
COMMENT ON COLUMN DISK_INFO.PRIORITY IS '优先级';
COMMENT ON COLUMN DISK_INFO.LAST_MODIFIER IS '最后修改人';
COMMENT ON COLUMN DISK_INFO.LAST_MODIFIED_TIME IS '最后修改时间';
COMMENT ON COLUMN DISK_INFO.STATUS IS '状态';
COMMENT ON COLUMN DISK_INFO.EXPIRE_TIME IS '过期时间';
COMMENT ON COLUMN DISK_INFO.CHECKOUT_STATUS IS '签出时间';
COMMENT ON COLUMN DISK_INFO.FILE_VERSION IS '文件版本';
COMMENT ON COLUMN DISK_INFO.SECURITY_LEVEL IS '安全级别';


