

-------------------------------------------------------------------------------
--  disk share
-------------------------------------------------------------------------------
CREATE TABLE DISK_SHARE(
        ID BIGINT NOT NULL,
	SHARE_TYPE VARCHAR(50),
	SHARE_TIME DATETIME,
	INFO_ID BIGINT,

	NAME VARCHAR(200),
	CREATOR VARCHAR(64),
	TYPE VARCHAR(64),
	DIR_TYPE INT,

	COUNT_VIEW INT,
	COUNT_SAVE INT,
	COUNT_DOWNLOAD INT,

        CONSTRAINT PK_DISK_SHARE PRIMARY KEY(ID),
	CONSTRAINT FK_DISK_SHARE_INFO FOREIGN KEY (INFO_ID) REFERENCES DISK_INFO(ID)
);

COMMENT ON TABLE DISK_SHARE IS '分享';
COMMENT ON COLUMN DISK_SHARE.ID IS '主键';
COMMENT ON COLUMN DISK_SHARE.SHARE_TYPE IS '分享类型';
COMMENT ON COLUMN DISK_SHARE.SHARE_TIME IS '分享时间';
COMMENT ON COLUMN DISK_SHARE.NAME IS '名称';
COMMENT ON COLUMN DISK_SHARE.CREATOR IS '创建人';
COMMENT ON COLUMN DISK_SHARE.TYPE IS '类型';
COMMENT ON COLUMN DISK_SHARE.DIR_TYPE IS '是否文件夹';
COMMENT ON COLUMN DISK_SHARE.COUNT_VIEW IS '浏览量';
COMMENT ON COLUMN DISK_SHARE.COUNT_SAVE IS '保存量';
COMMENT ON COLUMN DISK_SHARE.COUNT_DOWNLOAD IS '下载量';
COMMENT ON COLUMN DISK_SHARE.INFO_ID IS '分享信息';

