

ALTER TABLE DISK_INFO ADD COLUMN ORIGINAL_PARENT_ID BIGINT;
ALTER TABLE DISK_INFO ADD COLUMN LINK_TYPE INT;
ALTER TABLE DISK_INFO ADD COLUMN LINK_ID BIGINT;
ALTER TABLE DISK_INFO ADD COLUMN OWNER_ID VARCHAR(64);
ALTER TABLE DISK_INFO ADD COLUMN DELETE_STATUS VARCHAR(10);
ALTER TABLE DISK_INFO ADD COLUMN DELETE_TIME TIMESTAMP;
ALTER TABLE DISK_INFO ADD COLUMN PUBLIC_TYPE VARCHAR(50);
ALTER TABLE DISK_INFO ADD COLUMN PUBLIC_EDIT VARCHAR(50);

COMMENT ON COLUMN DISK_INFO.ORIGINAL_PARENT_ID IS '原上级文件夹';
COMMENT ON COLUMN DISK_INFO.LINK_TYPE IS '链接';
COMMENT ON COLUMN DISK_INFO.LINK_ID IS '链接原文件';
COMMENT ON COLUMN DISK_INFO.OWNER_ID IS '所有者id';
COMMENT ON COLUMN DISK_INFO.DELETE_STATUS IS '是否回收站顶级文件夹';
COMMENT ON COLUMN DISK_INFO.DELETE_TIME IS '回收站自动清理时间';
COMMENT ON COLUMN DISK_INFO.PUBLIC_TYPE IS '是否公开';
COMMENT ON COLUMN DISK_INFO.PUBLIC_EDIT IS '公开是否可编辑';


