

-------------------------------------------------------------------------------
--  disk upload
-------------------------------------------------------------------------------
CREATE TABLE DISK_UPLOAD(
    ID BIGINT NOT NULL,
    NAME VARCHAR(200),
    TYPE VARCHAR(50),
    SIZE BIGINT,
    LAST_MODIFIED BIGINT,
    CATALOG VARCHAR(10),

    USER_ID VARCHAR(64),
    INFO_ID BIGINT,
    FILE_ID BIGINT,
    FOLDER_ID BIGINT,
    FOLDER_PATH VARCHAR(200),
    PART_TYPE VARCHAR(50),
    PART_INDEX INT,
    PART_PARENT BIGINT,
    RANGE_START BIGINT,
    RANGE_END BIGINT,

    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    REASON VARCHAR(200),

	CREATOR VARCHAR(64),
	CREATE_TIME DATETIME,
	UPDATER VARCHAR(64),
	UPDATE_TIME DATETIME,
	STATUS VARCHAR(50),
    TENANT_ID VARCHAR(64),
    CONSTRAINT PK_DISK_UPLOAD PRIMARY KEY(ID)
);

COMMENT ON TABLE DISK_UPLOAD IS '上传';
COMMENT ON COLUMN DISK_UPLOAD.ID IS 'id';
COMMENT ON COLUMN DISK_UPLOAD.NAME IS '名称';
COMMENT ON COLUMN DISK_UPLOAD.TYPE IS '类型';
COMMENT ON COLUMN DISK_UPLOAD.SIZE IS '大小';
COMMENT ON COLUMN DISK_UPLOAD.LAST_MODIFIED IS '最后更新时间';
COMMENT ON COLUMN DISK_UPLOAD.CATALOG IS '分类root,part';
COMMENT ON COLUMN DISK_UPLOAD.USER_ID IS '对应帐号id';
COMMENT ON COLUMN DISK_UPLOAD.INFO_ID IS '节点id';
COMMENT ON COLUMN DISK_UPLOAD.FILE_ID IS '文件id';
COMMENT ON COLUMN DISK_UPLOAD.FOLDER_ID IS '文件夹id';
COMMENT ON COLUMN DISK_UPLOAD.FOLDER_PATH IS '文件夹路径';
COMMENT ON COLUMN DISK_UPLOAD.PART_TYPE IS '是否分片上传single,part';
COMMENT ON COLUMN DISK_UPLOAD.PART_INDEX IS '分片索引';
COMMENT ON COLUMN DISK_UPLOAD.PART_PARENT IS '分片根';
COMMENT ON COLUMN DISK_UPLOAD.RANGE_START IS '分片开始位置';
COMMENT ON COLUMN DISK_UPLOAD.RANGE_END IS '分片结束位置';
COMMENT ON COLUMN DISK_UPLOAD.START_TIME IS '开始时间';
COMMENT ON COLUMN DISK_UPLOAD.END_TIME IS '结束时间';
COMMENT ON COLUMN DISK_UPLOAD.REASON IS '失败原因';
COMMENT ON COLUMN DISK_UPLOAD.CREATOR IS '创建人';
COMMENT ON COLUMN DISK_UPLOAD.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN DISK_UPLOAD.UPDATER IS '更新人';
COMMENT ON COLUMN DISK_UPLOAD.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN DISK_UPLOAD.STATUS IS '状态';
COMMENT ON COLUMN DISK_UPLOAD.TENANT_ID IS '租户';

