

ALTER TABLE DISK_ACL ADD COLUMN ENTITY_REF VARCHAR(50);
ALTER TABLE DISK_ACL ADD COLUMN ENTITY_CATALOG VARCHAR(50);
ALTER TABLE DISK_ACL ADD COLUMN MASK INT;

ALTER TABLE DISK_ACL ADD COLUMN RULE_ID BIGINT;
ALTER TABLE DISK_ACL ADD CONSTRAINT FK_DISK_ACL_RULE FOREIGN KEY(RULE_ID) REFERENCES DISK_RULE(ID);

COMMENT ON TABLE DISK_ACL IS '权限';
COMMENT ON COLUMN DISK_ACL.ID IS 'id';
COMMENT ON COLUMN DISK_ACL.TYPE IS '类型';
COMMENT ON COLUMN DISK_ACL.REF IS '引用';
COMMENT ON COLUMN DISK_ACL.SHARE_ID IS '外键，共享';
COMMENT ON COLUMN DISK_ACL.ENTITY_REF IS '实体引用';
COMMENT ON COLUMN DISK_ACL.ENTITY_CATALOG IS '实体分类，owner, role, user';
COMMENT ON COLUMN DISK_ACL.MASK IS '掩码';
COMMENT ON COLUMN DISK_ACL.RULE_ID IS '外键，规则';

