

-------------------------------------------------------------------------------
--  disk member
-------------------------------------------------------------------------------
CREATE TABLE DISK_MEMBER(
    ID BIGINT NOT NULL,
    CATALOG VARCHAR(50),
    TYPE VARCHAR(50),
    NAME VARCHAR(200),
    MASK INT,
    DESCRIPTION VARCHAR(255),
    USER_ID VARCHAR(64),
    CREATOR VARCHAR(64),
    CREATE_TIME DATETIME,
    EXPIRE_TIME DATETIME,
    STATUS VARCHAR(50),
    PRIORITY INT,
    SPACE_ID BIGINT,
    SHARE_ID BIGINT,
    CONSTRAINT PK_DISK_MEMBER PRIMARY KEY(ID),
    CONSTRAINT FK_DISK_MEMBER_SPACE FOREIGN KEY (SPACE_ID) REFERENCES DISK_SPACE(ID),
    CONSTRAINT FK_DISK_MEMBER_SHARE FOREIGN KEY (SHARE_ID) REFERENCES DISK_SHARE(ID)
);

COMMENT ON TABLE DISK_MEMBER IS '文件成员';
COMMENT ON COLUMN DISK_MEMBER.ID IS '主键';
COMMENT ON COLUMN DISK_MEMBER.CATALOG IS '类型';
COMMENT ON COLUMN DISK_MEMBER.TYPE IS '分类';
COMMENT ON COLUMN DISK_MEMBER.NAME IS '名称';
COMMENT ON COLUMN DISK_MEMBER.MASK IS '掩码';
COMMENT ON COLUMN DISK_MEMBER.DESCRIPTION IS '备注';
COMMENT ON COLUMN DISK_MEMBER.USER_ID IS '成员';
COMMENT ON COLUMN DISK_MEMBER.CREATOR IS '创建人';
COMMENT ON COLUMN DISK_MEMBER.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN DISK_MEMBER.EXPIRE_TIME IS '过期时间';
COMMENT ON COLUMN DISK_MEMBER.STATUS IS '状态';
COMMENT ON COLUMN DISK_MEMBER.PRIORITY IS '优先级';
COMMENT ON COLUMN DISK_MEMBER.SPACE_ID IS '所属空间';
COMMENT ON COLUMN DISK_MEMBER.SHARE_ID IS '对应分享';

