

-------------------------------------------------------------------------------
--  disk version
-------------------------------------------------------------------------------
CREATE TABLE DISK_VERSION(
    ID BIGINT NOT NULL,
	NAME VARCHAR(200),
	DESCRIPTION VARCHAR(255),

	TYPE VARCHAR(50),
	FILE_SIZE BIGINT,
	CREATOR VARCHAR(64),
	CREATE_TIME DATETIME,
	FILE_PATH VARCHAR(200),
	PRIORITY INT,
	FILE_VERSION VARCHAR(50),

	LAST_MODIFIER VARCHAR(64),
	LAST_MODIFIED_TIME DATETIME,
	STATUS VARCHAR(50),

	INFO_ID BIGINT,

    CONSTRAINT PK_DISK_VERSION PRIMARY KEY(ID),
	CONSTRAINT FK_DISK_VERSION_INFO FOREIGN KEY (INFO_ID) REFERENCES DISK_INFO(ID)
);

COMMENT ON TABLE DISK_VERSION IS '文件版本';
COMMENT ON COLUMN DISK_VERSION.ID IS '主键';
COMMENT ON COLUMN DISK_VERSION.NAME IS '名称';
COMMENT ON COLUMN DISK_VERSION.DESCRIPTION IS '备注';
COMMENT ON COLUMN DISK_VERSION.TYPE IS '分类';
COMMENT ON COLUMN DISK_VERSION.FILE_SIZE IS '文件大小';
COMMENT ON COLUMN DISK_VERSION.CREATOR IS '创建人';
COMMENT ON COLUMN DISK_VERSION.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN DISK_VERSION.FILE_PATH IS '文件路径';
COMMENT ON COLUMN DISK_VERSION.PRIORITY IS '优先级';
COMMENT ON COLUMN DISK_VERSION.FILE_VERSION IS '文件版本';
COMMENT ON COLUMN DISK_VERSION.LAST_MODIFIER IS '最后修改人';
COMMENT ON COLUMN DISK_VERSION.LAST_MODIFIED_TIME IS '最后修改时间';
COMMENT ON COLUMN DISK_VERSION.STATUS IS '状态';
COMMENT ON COLUMN DISK_VERSION.INFO_ID IS '对应文件';

