

-------------------------------------------------------------------------------
--  disk sid
-------------------------------------------------------------------------------
CREATE TABLE DISK_SID(
    ID BIGINT NOT NULL,
    CATALOG VARCHAR(50),
    VALUE VARCHAR(100),
    NAME VARCHAR(100),
    REF VARCHAR(100),
    CREATOR VARCHAR(64),
    CREATE_TIME DATETIME,
    UPDATER VARCHAR(64),
    UPDATE_TIME DATETIME,
    STATUS VARCHAR(50),

    CONSTRAINT PK_DISK_SID PRIMARY KEY(ID)
);

CREATE INDEX IDX_DISK_SID_VALUE ON DISK_SID(VALUE);

COMMENT ON TABLE DISK_SID IS '实体';
COMMENT ON COLUMN DISK_SID.ID IS '主键';
COMMENT ON COLUMN DISK_SID.CATALOG IS '类型';
COMMENT ON COLUMN DISK_SID.VALUE IS '数值';
COMMENT ON COLUMN DISK_SID.NAME IS '名称';
COMMENT ON COLUMN DISK_SID.REF IS '外部引用';
COMMENT ON COLUMN DISK_SID.CREATOR IS '创建人';
COMMENT ON COLUMN DISK_SID.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN DISK_SID.UPDATER IS '修改人';
COMMENT ON COLUMN DISK_SID.UPDATE_TIME IS '修改时间';
COMMENT ON COLUMN DISK_SID.STATUS IS '状态';



