

ALTER TABLE DISK_ACL ADD COLUMN SID_ID BIGINT;
ALTER TABLE DISK_ACL ADD COLUMN PRIORITY INT;

COMMENT ON COLUMN DISK_ACL.SID_ID IS '实体标识';
COMMENT ON COLUMN DISK_ACL.PRIORITY IS '排序';

ALTER TABLE DISK_ACL ADD FOREIGN KEY(SID_ID) REFERENCES DISK_SID(ID);

