

-------------------------------------------------------------------------------
--  disk tag info
-------------------------------------------------------------------------------
CREATE TABLE DISK_TAG_INFO(
    ID BIGINT NOT NULL,
    TYPE VARCHAR(50),
    TAG_ID BIGINT,
    INFO_ID BIGINT,
    PRIORITY INT,
    TENANT_ID VARCHAR(64),
    CONSTRAINT PK_DISK_TAG_INFO PRIMARY KEY(ID),
    CONSTRAINT FK_DISK_TAG_INFO_TAG FOREIGN KEY(TAG_ID) REFERENCES DISK_TAG(ID),
    CONSTRAINT FK_DISK_TAG_INFO_INFO FOREIGN KEY(INFO_ID) REFERENCES DISK_INFO(ID)
);

COMMENT ON TABLE DISK_TAG_INFO IS '标签实体关联';
COMMENT ON COLUMN DISK_TAG_INFO.ID IS 'id';
COMMENT ON COLUMN DISK_TAG_INFO.TYPE IS '类型';
COMMENT ON COLUMN DISK_TAG_INFO.TAG_ID IS '外键，标签';
COMMENT ON COLUMN DISK_TAG_INFO.INFO_ID IS '外键，实体';
COMMENT ON COLUMN DISK_TAG_INFO.PRIORITY IS '排序';
COMMENT ON COLUMN DISK_TAG_INFO.TENANT_ID IS '租户';

