

ALTER TABLE DISK_INFO ADD COLUMN INHERIT VARCHAR(50);

ALTER TABLE DISK_INFO ADD COLUMN RULE_ID BIGINT;
ALTER TABLE DISK_INFO ADD CONSTRAINT FK_DISK_INFO_RULE FOREIGN KEY(RULE_ID) REFERENCES DISK_RULE(ID);

COMMENT ON COLUMN DISK_INFO.INHERIT IS '继承';
COMMENT ON COLUMN DISK_INFO.RULE_ID IS '规则';

