

ALTER TABLE DISK_SHARE ADD COLUMN SHARE_CODE VARCHAR(50);
ALTER TABLE DISK_SHARE ADD COLUMN SHARE_PASSWORD VARCHAR(50);

COMMENT ON COLUMN DISK_SHARE.SHARE_CODE IS 'token';
COMMENT ON COLUMN DISK_SHARE.SHARE_PASSWORD IS '密码';

