

UPDATE AUTH_MENU SET DISPLAY='false' where ID=91;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=101;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=111;

UPDATE AUTH_MENU SET DISPLAY='false' where ID=604;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=605;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=606;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=607;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=608;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=609;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=610;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=611;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=612;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=613;

UPDATE AUTH_MENU SET DISPLAY='false' where ID=705;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=706;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=707;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=708;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=709;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=710;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=711;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=712;
UPDATE AUTH_MENU SET DISPLAY='false' where ID=713;

