

-------------------------------------------------------------------------------
--  notification template provider
-------------------------------------------------------------------------------
CREATE TABLE NOTIFICATION_TEMPLATE_PROVIDER(
    TEMPLATE_ID BIGINT,
    PROVIDER_ID BIGINT,

    CONSTRAINT PK_NOTIFICATION_TEMPLATE_PROVIDER PRIMARY KEY(TEMPLATE_ID, PROVIDER_ID),
    CONSTRAINT PK_NOTIFICATION_TEMPLATE_PROVIDER_T FOREIGN KEY (TEMPLATE_ID) REFERENCES NOTIFICATION_TEMPLATE(ID),
    CONSTRAINT PK_NOTIFICATION_TEMPLATE_PROVIDER_P FOREIGN KEY (PROVIDER_ID) REFERENCES NOTIFICATION_PROVIDER(ID)
);

COMMENT ON TABLE NOTIFICATION_TEMPLATE_PROVIDER IS '通知模板注册供应商';
COMMENT ON COLUMN NOTIFICATION_TEMPLATE_PROVIDER.TEMPLATE_ID IS '模板';
COMMENT ON COLUMN NOTIFICATION_TEMPLATE_PROVIDER.PROVIDER_ID IS '供应商';

