

-------------------------------------------------------------------------------
--  plm project
-------------------------------------------------------------------------------
CREATE TABLE PLM_PROJECT(
        ID BIGINT NOT NULL,
	CODE VARCHAR(50),
	NAME VARCHAR(200),
	LOGO VARCHAR(200),
	SUMMARY TEXT,
	WIKI_URL VARCHAR(200),
	SOURCE_URL VARCHAR(200),
	URL VARCHAR(200),
	LEADER_ID VARCHAR(64),
	PRIORITY INT,
	STATUS VARCHAR(50),
	CREATE_TIME DATETIME,
	USER_ID VARCHAR(64),
	CATEGORY_ID BIGINT,
	CONSTRAINT PK_PLM_PROJECT PRIMARY KEY(ID),
        CONSTRAINT FK_PIM_PROJECT_CATEGORY FOREIGN KEY(CATEGORY_ID) REFERENCES PLM_CATEGORY(ID)
) ENGINE=INNODB CHARSET=UTF8;

