

ALTER TABLE WHITELIST_TYPE ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE WHITELIST_APP ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE WHITELIST_HOST ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE WHITELIST_IP ADD COLUMN TENANT_ID VARCHAR(64);

