

-------------------------------------------------------------------------------
--  keyvalue record
-------------------------------------------------------------------------------
CREATE TABLE KV_RECORD(
        ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
	CATEGORY VARCHAR(200),
	STATUS INT,
	REF VARCHAR(200),
        CONSTRAINT PK_KV_RECORD PRIMARY KEY(ID)
);

COMMENT ON TABLE KV_RECORD IS 'keyvalue存储';
COMMENT ON COLUMN KV_RECORD.ID IS '主键';
COMMENT ON COLUMN KV_RECORD.CATEGORY IS '分类';
COMMENT ON COLUMN KV_RECORD.STATUS IS '状态';
COMMENT ON COLUMN KV_RECORD.REF IS '引用';

