

ALTER TABLE KV_RECORD ADD COlUMN USER_ID VARCHAR(64);
ALTER TABLE KV_RECORD ADD COLUMN CREATE_TIME TIMESTAMP;

COMMENT ON COLUMN KV_RECORD.USER_ID IS '操作人';
COMMENT ON COLUMN KV_RECORD.CREATE_TIME IS '创建时间';
