

ALTER TABLE KV_RECORD ADD COlUMN NAME VARCHAR(200);
ALTER TABLE KV_RECORD ADD COLUMN FORM_TEMPLATE_CODE VARCHAR(200);

COMMENT ON COLUMN KV_RECORD.NAME IS '名称';
COMMENT ON COLUMN KV_RECORD.FORM_TEMPLATE_CODE IS '表单模板ID';
