

ALTER TABLE FORM_TEMPLATE ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE FORM_TEMPLATE ADD COLUMN USER_ID VARCHAR(64);
ALTER TABLE FORM_TEMPLATE ADD COLUMN CREATE_TIME DATETIME;
ALTER TABLE FORM_SCHEMA ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;

