

ALTER TABLE DISK_INFO ADD COLUMN ORIGINAL_PARENT_ID BIGINT;
ALTER TABLE DISK_INFO ADD COLUMN LINK_TYPE INT;
ALTER TABLE DISK_INFO ADD COLUMN LINK_ID BIGINT;
ALTER TABLE DISK_INFO ADD COLUMN OWNER_ID VARCHAR(64);
ALTER TABLE DISK_INFO ADD COLUMN DELETE_STATUS VARCHAR(10);
ALTER TABLE DISK_INFO ADD COLUMN DELETE_TIME TIMESTAMP;
ALTER TABLE DISK_INFO ADD COLUMN PUBLIC_TYPE VARCHAR(50);
ALTER TABLE DISK_INFO ADD COLUMN PUBLIC_EDIT VARCHAR(50);











