

INSERT INTO GROUP_TYPE(ID,NAME,USER_REPO_REF,SCOPE_ID) VALUES(1,'部门','1','1');

INSERT INTO GROUP_BASE(ID,NAME,STATUS,GROUP_TYPE_ID,USER_REPO_REF,SCOPE_ID) VALUES(1,'Mossle科技有限公司',1,1,'1','1');
INSERT INTO GROUP_BASE(ID,NAME,STATUS,GROUP_TYPE_ID,USER_REPO_REF,SCOPE_ID) VALUES(2,'市场部',1,1,'1','1');
INSERT INTO GROUP_BASE(ID,NAME,STATUS,GROUP_TYPE_ID,USER_REPO_REF,SCOPE_ID) VALUES(3,'财务部',1,1,'1','1');
INSERT INTO GROUP_BASE(ID,NAME,STATUS,GROUP_TYPE_ID,USER_REPO_REF,SCOPE_ID) VALUES(4,'人事部',1,1,'1','1');
INSERT INTO GROUP_BASE(ID,NAME,STATUS,GROUP_TYPE_ID,USER_REPO_REF,SCOPE_ID) VALUES(5,'研发部',1,1,'1','1');
INSERT INTO GROUP_BASE(ID,NAME,STATUS,GROUP_TYPE_ID,USER_REPO_REF,SCOPE_ID) VALUES(6,'平台组',1,1,'1','1');
INSERT INTO GROUP_BASE(ID,NAME,STATUS,GROUP_TYPE_ID,USER_REPO_REF,SCOPE_ID) VALUES(7,'OA组',1,1,'1','1');

