

ALTER TABLE ORG_COMPANY ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;
ALTER TABLE ORG_DEPARTMENT ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;
ALTER TABLE JOB_GRADE ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;
ALTER TABLE JOB_LEVEL ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;
ALTER TABLE JOB_TYPE ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;
ALTER TABLE JOB_TITLE ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;
ALTER TABLE JOB_INFO ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;
ALTER TABLE JOB_USER ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;

