
CREATE TABLE DELEGATE_HISTORY(
	ID BIGINT NOT NULL,
	ASSIGNEE VARCHAR(200),
	ATTORNEY VARCHAR(200),
	DELEGATE_TIME DATETIME,
	TASK_ID VARCHAR(100),
	PROCESS_DEFINITION_ID VARCHAR(100),
	TASK_DEFINITION_KEY VARCHAR(100),
	STATUS INTEGER,
	TENANT_ID VARCHAR(64),
        CONSTRAINT PK_DELEGATE_HISTORY PRIMARY KEY(ID)
) ENGINE=INNODB CHARSET=UTF8;

