
CREATE TABLE DELEGATE_INFO(
	ID BIGINT NOT NULL,
	ASSIGNEE VARCHAR(200),
	ATTORNEY VARCHAR(200),
	START_TIME DATETIME,
	END_TIME DATETIME,
	PROCESS_DEFINITION_ID VARCHAR(100),
	TASK_DEFINITION_KEY VARCHAR(100),
	STATUS INTEGER,
	TENANT_ID VARCHAR(64),
        CONSTRAINT PK_DELEGATE_INFO PRIMARY KEY(ID)
) ENGINE=INNODB CHARSET=UTF8;
