package com.mossle.internal.whitelist.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WhitelistInfo .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "WHITELIST_INFO")
public class WhitelistInfo implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private WhitelistService whitelistService;

    /** null. */
    private WhitelistApp whitelistApp;

    /** null. */
    private String code;

    /** null. */
    private String name;

    /** null. */
    private String userId;

    /** null. */
    private String description;

    /** null. */
    private Date createTime;

    /** null. */
    private Date updateTime;

    /** null. */
    private String status;

    public WhitelistInfo() {
    }

    public WhitelistInfo(Long id) {
        this.id = id;
    }

    public WhitelistInfo(Long id, WhitelistService whitelistService,
            WhitelistApp whitelistApp, String code, String name, String userId,
            String description, Date createTime, Date updateTime, String status) {
        this.id = id;
        this.whitelistService = whitelistService;
        this.whitelistApp = whitelistApp;
        this.code = code;
        this.name = name;
        this.userId = userId;
        this.description = description;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.status = status;
    }

    /** @return null. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SERVICE_ID")
    public WhitelistService getWhitelistService() {
        return this.whitelistService;
    }

    /**
     * @param whitelistService
     *            null.
     */
    public void setWhitelistService(WhitelistService whitelistService) {
        this.whitelistService = whitelistService;
    }

    /** @return null. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "APP_ID")
    public WhitelistApp getWhitelistApp() {
        return this.whitelistApp;
    }

    /**
     * @param whitelistApp
     *            null.
     */
    public void setWhitelistApp(WhitelistApp whitelistApp) {
        this.whitelistApp = whitelistApp;
    }

    /** @return null. */
    @Column(name = "CODE", length = 50)
    public String getCode() {
        return this.code;
    }

    /**
     * @param code
     *            null.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /** @return null. */
    @Column(name = "NAME", length = 50)
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            null.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** @return null. */
    @Column(name = "USER_ID", length = 50)
    public String getUserId() {
        return this.userId;
    }

    /**
     * @param userId
     *            null.
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /** @return null. */
    @Column(name = "DESCRIPTION", length = 200)
    public String getDescription() {
        return this.description;
    }

    /**
     * @param description
     *            null.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /** @return null. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_TIME", length = 26)
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * @param createTime
     *            null.
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /** @return null. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_TIME", length = 26)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    /**
     * @param updateTime
     *            null.
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /** @return null. */
    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    /**
     * @param status
     *            null.
     */
    public void setStatus(String status) {
        this.status = status;
    }
}
