

-------------------------------------------------------------------------------
--  account dept
-------------------------------------------------------------------------------
CREATE TABLE ACCOUNT_DEPT(
    ID BIGINT NOT NULL,
    CODE VARCHAR(50),
    NAME VARCHAR(50),
    REF VARCHAR(100),
    SUPERIOUR VARCHAR(100),
    PRIORITY INT,
    PARENT_ID BIGINT,
    CONSTRAINT PK_ACCOUNT_DEPT PRIMARY KEY(ID),
    CONSTRAINT FK_ACCOUNT_DEPT_PARENT FOREIGN KEY(PARENT_ID) REFERENCES ACCOUNT_DEPT(ID)
);

COMMENT ON TABLE ACCOUNT_DEPT IS '标识';
COMMENT ON COLUMN ACCOUNT_DEPT.ID IS '主键';
COMMENT ON COLUMN ACCOUNT_DEPT.CODE IS '标识';
COMMENT ON COLUMN ACCOUNT_DEPT.NAME IS '名称';
COMMENT ON COLUMN ACCOUNT_DEPT.REF IS '外部引用';
COMMENT ON COLUMN ACCOUNT_DEPT.SUPERIOUR IS '负责人';
COMMENT ON COLUMN ACCOUNT_DEPT.PRIORITY IS '排序';
COMMENT ON COLUMN ACCOUNT_DEPT.PARENT_ID IS '上级部门';

