

alter table PERSON_INFO add column DISPLAY_NAME VARCHAR(50);
alter table PERSON_INFO add column TYPE VARCHAR(50);
alter table PERSON_INFO add column STATUS VARCHAR(50);

COMMENT ON COLUMN PERSON_INFO.DISPLAY_NAME IS '显示名';
COMMENT ON COLUMN PERSON_INFO.TYPE IS '类型';
COMMENT ON COLUMN PERSON_INFO.STATUS IS '状态';

