

-------------------------------------------------------------------------------
-- account avatar
-------------------------------------------------------------------------------
CREATE TABLE ACCOUNT_AVATAR(
        ID BIGINT NOT NULL,
	TYPE VARCHAR(50),
	CODE VARCHAR(200),
	ACCOUNT_ID BIGINT,
        CONSTRAINT PK_ACCOUNT_AVATAR PRIMARY KEY(ID),
        CONSTRAINT FK_ACCOUNT_AVATAR_ACCOUNT FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT_INFO(ID)
);

COMMENT ON TABLE ACCOUNT_AVATAR IS '头像';
COMMENT ON COLUMN ACCOUNT_AVATAR.ID IS '主键';
COMMENT ON COLUMN ACCOUNT_AVATAR.TYPE IS '类型';
COMMENT ON COLUMN ACCOUNT_AVATAR.CODE IS '附件路径';
COMMENT ON COLUMN ACCOUNT_AVATAR.ACCOUNT_ID IS '外键，账号信息';

