

INSERT INTO JAVAMAIL_CONFIG(ID,USERNAME,PASSWORD,RECEIVE_TYPE,RECEIVE_HOST,RECEIVE_PORT,RECEIVE_SECURE,SEND_TYPE,SEND_HOST,SEND_PORT,SEND_SECURE,PRIORITY,USER_ID) VALUES(1,'lingo@mossle.com','~lemon2mossle','pop3','mail.mossle.com','995','ssl-all','smtp','mail.mossle.com','465','ssl-all',1,1);

