
CREATE TABLE PARTY_TYPE(
        ID BIGINT AUTO_INCREMENT,
        NAME VARCHAR(50),
	PERSON INTEGER,
	SCOPE_ID VARCHAR(50),
        CONSTRAINT PK_PARTY_TYPE PRIMARY KEY(ID)
) ENGINE=INNODB CHARSET=UTF8;
