

ALTER TABLE PARTY_STRUCT DROP FOREIGN KEY FK_PARTY_STRUCT_TYPE;
ALTER TABLE PARTY_STRUCT DROP FOREIGN KEY FK_PARTY_STRUCT_PARENT;
ALTER TABLE PARTY_STRUCT DROP FOREIGN KEY FK_PARTY_STRUCT_CHILD;
ALTER TABLE PARTY_STRUCT DROP PRIMARY KEY;
ALTER TABLE PARTY_STRUCT DROP FOREIGN KEY FK_PARTY_STRUCT_DIM;
ALTER TABLE PARTY_STRUCT DROP COLUMN DIM_ID;
ALTER TABLE PARTY_STRUCT CHANGE COLUMN PARENT_ENTITY_ID PARENT_ENTITY_ID BIGINT NULL;
ALTER TABLE PARTY_STRUCT ADD COLUMN ID BIGINT;
ALTER TABLE PARTY_STRUCT ADD CONSTRAINT PK_PARTY_STRUCT PRIMARY KEY(ID);
ALTER TABLE PARTY_STRUCT ADD CONSTRAINT FK_PARTY_STRUCT_TYPE FOREIGN KEY(STRUCT_TYPE_ID) REFERENCES PARTY_STRUCT_TYPE(ID);
ALTER TABLE PARTY_STRUCT ADD CONSTRAINT FK_PARTY_STRUCT_PARENT FOREIGN KEY(PARENT_ENTITY_ID) REFERENCES PARTY_ENTITY(ID);
ALTER TABLE PARTY_STRUCT ADD CONSTRAINT FK_PARTY_STRUCT_CHILD FOREIGN KEY(CHILD_ENTITY_ID) REFERENCES PARTY_ENTITY(ID);

ALTER TABLE PARTY_STRUCT ADD COLUMN PART_TIME INT;
ALTER TABLE PARTY_STRUCT ADD COLUMN LINK INT;
ALTER TABLE PARTY_STRUCT ADD COLUMN ADMIN INT;
ALTER TABLE PARTY_STRUCT DROP COLUMN STATUS;






