

ALTER TABLE PARTY_STRUCT_TYPE ADD COLUMN DISPLAY VARCHAR(200);
ALTER TABLE PARTY_STRUCT_TYPE ADD COLUMN TYPE VARCHAR(50);

ALTER TABLE PARTY_STRUCT ADD COLUMN TYPE VARCHAR(50);

ALTER TABLE PARTY_ENTITY ADD COLUMN CODE VARCHAR(50);
