package com.mossle.internal.store.persistence.domain;

// Generated by Hibernate Tools
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StoreApp .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "STORE_APP")
public class StoreApp implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private String name;

    /** null. */
    private String groupName;

    /** null. */
    private String modelCode;

    /** null. */
    private Integer priority;

    /** null. */
    private String appId;

    /** null. */
    private String appKey;

    /** null. */
    private String status;

    /** null. */
    private String description;

    public StoreApp() {
    }

    public StoreApp(Long id) {
        this.id = id;
    }

    public StoreApp(Long id, String name, String groupName, String modelCode,
            Integer priority, String appId, String appKey, String status,
            String description) {
        this.id = id;
        this.name = name;
        this.groupName = groupName;
        this.modelCode = modelCode;
        this.priority = priority;
        this.appId = appId;
        this.appKey = appKey;
        this.status = status;
        this.description = description;
    }

    /** @return null. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @Column(name = "NAME", length = 50)
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            null.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** @return null. */
    @Column(name = "GROUP_NAME", length = 200)
    public String getGroupName() {
        return this.groupName;
    }

    /**
     * @param groupName
     *            null.
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /** @return null. */
    @Column(name = "MODEL_CODE", length = 50)
    public String getModelCode() {
        return this.modelCode;
    }

    /**
     * @param modelCode
     *            null.
     */
    public void setModelCode(String modelCode) {
        this.modelCode = modelCode;
    }

    /** @return null. */
    @Column(name = "PRIORITY")
    public Integer getPriority() {
        return this.priority;
    }

    /**
     * @param priority
     *            null.
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /** @return null. */
    @Column(name = "APP_ID", length = 200)
    public String getAppId() {
        return this.appId;
    }

    /**
     * @param appId
     *            null.
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /** @return null. */
    @Column(name = "APP_KEY", length = 200)
    public String getAppKey() {
        return this.appKey;
    }

    /**
     * @param appKey
     *            null.
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey;
    }

    /** @return null. */
    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    /**
     * @param status
     *            null.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /** @return null. */
    @Column(name = "DESCRIPTION", length = 200)
    public String getDescription() {
        return this.description;
    }

    /**
     * @param description
     *            null.
     */
    public void setDescription(String description) {
        this.description = description;
    }
}
