


INSERT INTO ORG_COMPANY(ID,NAME,STATUS,SCOPE_ID) VALUES(1,'Mossle科技有限公司',1,'1');



INSERT INTO ORG_DEPARTMENT(ID,NAME,STATUS,SCOPE_ID) VALUES(1,'市场部',1,'1');
INSERT INTO ORG_DEPARTMENT(ID,NAME,STATUS,SCOPE_ID) VALUES(2,'财务部',1,'1');
INSERT INTO ORG_DEPARTMENT(ID,NAME,STATUS,SCOPE_ID) VALUES(3,'人事部',1,'1');
INSERT INTO ORG_DEPARTMENT(ID,NAME,STATUS,SCOPE_ID) VALUES(4,'研发部',1,'1');



INSERT INTO ORG_GROUP(ID,NAME,STATUS,SCOPE_ID) VALUES(1,'平台组',1,'1');
INSERT INTO ORG_GROUP(ID,NAME,STATUS,SCOPE_ID) VALUES(2,'OA组',1,'1');



INSERT INTO ORG_POSITION_TYPE(ID,NAME,SCOPE_ID) VALUES(1,'研发','1');
INSERT INTO ORG_POSITION_TYPE(ID,NAME,SCOPE_ID) VALUES(2,'产品','1');



INSERT INTO ORG_POSITION(ID,NAME,TYPE_ID,SCOPE_ID) VALUES(1,'rd',1,'1');
INSERT INTO ORG_POSITION(ID,NAME,TYPE_ID,SCOPE_ID) VALUES(2,'pm',2,'1');


