

ALTER TABLE SENDMAIL_CONFIG CHANGE SCOPE_ID TENANT_ID VARCHAR(200);
ALTER TABLE SENDMAIL_TEMPLATE CHANGE SCOPE_ID TENANT_ID VARCHAR(200);
ALTER TABLE SENDMAIL_ATTACHMENT CHANGE SCOPE_ID TENANT_ID VARCHAR(200);
ALTER TABLE SENDMAIL_QUEUE CHANGE SCOPE_ID TENANT_ID VARCHAR(200);
ALTER TABLE SENDMAIL_HISTORY CHANGE SCOPE_ID TENANT_ID VARCHAR(200);

