package com.mossle.ticket.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TicketInfo 工单信息.
 * 
 * @author Lingo
 */
@Entity
@Table(name = "TICKET_INFO")
public class TicketInfo implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** ID. */
    private Long id;

    /** 群组. */
    private TicketGroup ticketGroup;

    /** 分类. */
    private TicketCatalog ticketCatalog;

    /** 编号. */
    private String code;

    /** 名称. */
    private String name;

    /** 内容. */
    private String content;

    /** 创建人. */
    private String creator;

    /** 状态. */
    private String status;

    /** 创建时间. */
    private Date createTime;

    /** 分配人. */
    private String assignee;

    /** 更新时间. */
    private Date updateTime;

    /** 是否问卷调研. */
    private String survey;

    /** 问卷信息. */
    private String surveyMessage;

    /** 优先级. */
    private Integer priority;

    /** 来源. */
    private String source;

    /** 解决时间. */
    private Date resolveTime;

    /** 解决状态. */
    private String resolveStatus;

    /** 关闭时间. */
    private Date closeTime;

    /** 关闭状态. */
    private String closeStatus;

    /** . */
    private Set<TicketComment> ticketComments = new HashSet<TicketComment>(0);

    /** . */
    private Set<TicketAttachment> ticketAttachments = new HashSet<TicketAttachment>(
            0);

    public TicketInfo() {
    }

    public TicketInfo(Long id) {
        this.id = id;
    }

    public TicketInfo(Long id, TicketGroup ticketGroup,
            TicketCatalog ticketCatalog, String code, String name,
            String content, String creator, String status, Date createTime,
            String assignee, Date updateTime, String survey,
            String surveyMessage, Integer priority, String source,
            Date resolveTime, String resolveStatus, Date closeTime,
            String closeStatus, Set<TicketComment> ticketComments,
            Set<TicketAttachment> ticketAttachments) {
        this.id = id;
        this.ticketGroup = ticketGroup;
        this.ticketCatalog = ticketCatalog;
        this.code = code;
        this.name = name;
        this.content = content;
        this.creator = creator;
        this.status = status;
        this.createTime = createTime;
        this.assignee = assignee;
        this.updateTime = updateTime;
        this.survey = survey;
        this.surveyMessage = surveyMessage;
        this.priority = priority;
        this.source = source;
        this.resolveTime = resolveTime;
        this.resolveStatus = resolveStatus;
        this.closeTime = closeTime;
        this.closeStatus = closeStatus;
        this.ticketComments = ticketComments;
        this.ticketAttachments = ticketAttachments;
    }

    /** @return ID. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            ID.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return 群组. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GROUP_ID")
    public TicketGroup getTicketGroup() {
        return this.ticketGroup;
    }

    /**
     * @param ticketGroup
     *            群组.
     */
    public void setTicketGroup(TicketGroup ticketGroup) {
        this.ticketGroup = ticketGroup;
    }

    /** @return 分类. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CATALOG_ID")
    public TicketCatalog getTicketCatalog() {
        return this.ticketCatalog;
    }

    /**
     * @param ticketCatalog
     *            分类.
     */
    public void setTicketCatalog(TicketCatalog ticketCatalog) {
        this.ticketCatalog = ticketCatalog;
    }

    /** @return 编号. */
    @Column(name = "CODE", length = 200)
    public String getCode() {
        return this.code;
    }

    /**
     * @param code
     *            编号.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /** @return 名称. */
    @Column(name = "NAME", length = 200)
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            名称.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** @return 内容. */
    @Column(name = "CONTENT", length = 65535)
    public String getContent() {
        return this.content;
    }

    /**
     * @param content
     *            内容.
     */
    public void setContent(String content) {
        this.content = content;
    }

    /** @return 创建人. */
    @Column(name = "CREATOR", length = 64)
    public String getCreator() {
        return this.creator;
    }

    /**
     * @param creator
     *            创建人.
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /** @return 状态. */
    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    /**
     * @param status
     *            状态.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /** @return 创建时间. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_TIME", length = 26)
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * @param createTime
     *            创建时间.
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /** @return 分配人. */
    @Column(name = "ASSIGNEE", length = 64)
    public String getAssignee() {
        return this.assignee;
    }

    /**
     * @param assignee
     *            分配人.
     */
    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    /** @return 更新时间. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATE_TIME", length = 26)
    public Date getUpdateTime() {
        return this.updateTime;
    }

    /**
     * @param updateTime
     *            更新时间.
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /** @return 是否问卷调研. */
    @Column(name = "SURVEY", length = 50)
    public String getSurvey() {
        return this.survey;
    }

    /**
     * @param survey
     *            是否问卷调研.
     */
    public void setSurvey(String survey) {
        this.survey = survey;
    }

    /** @return 问卷信息. */
    @Column(name = "SURVEY_MESSAGE", length = 200)
    public String getSurveyMessage() {
        return this.surveyMessage;
    }

    /**
     * @param surveyMessage
     *            问卷信息.
     */
    public void setSurveyMessage(String surveyMessage) {
        this.surveyMessage = surveyMessage;
    }

    /** @return 优先级. */
    @Column(name = "PRIORITY")
    public Integer getPriority() {
        return this.priority;
    }

    /**
     * @param priority
     *            优先级.
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /** @return 来源. */
    @Column(name = "SOURCE", length = 50)
    public String getSource() {
        return this.source;
    }

    /**
     * @param source
     *            来源.
     */
    public void setSource(String source) {
        this.source = source;
    }

    /** @return 解决时间. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "RESOLVE_TIME", length = 26)
    public Date getResolveTime() {
        return this.resolveTime;
    }

    /**
     * @param resolveTime
     *            解决时间.
     */
    public void setResolveTime(Date resolveTime) {
        this.resolveTime = resolveTime;
    }

    /** @return 解决状态. */
    @Column(name = "RESOLVE_STATUS", length = 50)
    public String getResolveStatus() {
        return this.resolveStatus;
    }

    /**
     * @param resolveStatus
     *            解决状态.
     */
    public void setResolveStatus(String resolveStatus) {
        this.resolveStatus = resolveStatus;
    }

    /** @return 关闭时间. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CLOSE_TIME", length = 26)
    public Date getCloseTime() {
        return this.closeTime;
    }

    /**
     * @param closeTime
     *            关闭时间.
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /** @return 关闭状态. */
    @Column(name = "CLOSE_STATUS", length = 50)
    public String getCloseStatus() {
        return this.closeStatus;
    }

    /**
     * @param closeStatus
     *            关闭状态.
     */
    public void setCloseStatus(String closeStatus) {
        this.closeStatus = closeStatus;
    }

    /** @return . */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ticketInfo")
    public Set<TicketComment> getTicketComments() {
        return this.ticketComments;
    }

    /**
     * @param ticketComments
     *            .
     */
    public void setTicketComments(Set<TicketComment> ticketComments) {
        this.ticketComments = ticketComments;
    }

    /** @return . */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ticketInfo")
    public Set<TicketAttachment> getTicketAttachments() {
        return this.ticketAttachments;
    }

    /**
     * @param ticketAttachments
     *            .
     */
    public void setTicketAttachments(Set<TicketAttachment> ticketAttachments) {
        this.ticketAttachments = ticketAttachments;
    }
}
