package com.mossle.ticket.persistence.domain;

// Generated by Hibernate Tools
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TicketGroup .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "TICKET_GROUP")
public class TicketGroup implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private String name;

    /** null. */
    private String description;

    /** . */
    private Set<TicketInfo> ticketInfos = new HashSet<TicketInfo>(0);

    /** . */
    private Set<TicketMember> ticketMembers = new HashSet<TicketMember>(0);

    public TicketGroup() {
    }

    public TicketGroup(Long id) {
        this.id = id;
    }

    public TicketGroup(Long id, String name, String description,
            Set<TicketInfo> ticketInfos, Set<TicketMember> ticketMembers) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.ticketInfos = ticketInfos;
        this.ticketMembers = ticketMembers;
    }

    /** @return null. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @Column(name = "NAME", length = 200)
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            null.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** @return null. */
    @Column(name = "DESCRIPTION", length = 200)
    public String getDescription() {
        return this.description;
    }

    /**
     * @param description
     *            null.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /** @return . */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ticketGroup")
    public Set<TicketInfo> getTicketInfos() {
        return this.ticketInfos;
    }

    /**
     * @param ticketInfos
     *            .
     */
    public void setTicketInfos(Set<TicketInfo> ticketInfos) {
        this.ticketInfos = ticketInfos;
    }

    /** @return . */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ticketGroup")
    public Set<TicketMember> getTicketMembers() {
        return this.ticketMembers;
    }

    /**
     * @param ticketMembers
     *            .
     */
    public void setTicketMembers(Set<TicketMember> ticketMembers) {
        this.ticketMembers = ticketMembers;
    }
}
