

INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,TENANT_ID) VALUES(30011,3,'行政部','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,TENANT_ID) VALUES(30012,3,'销售部','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,TENANT_ID) VALUES(30013,3,'客服部','1');

INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10008,1,'Robot','8','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10009,1,'Bob','9','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10010,1,'Alice','10','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10011,1,'Mike','11','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10012,1,'Justin','12','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10013,1,'Tom','13','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10014,1,'James','14','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10015,1,'Joe','15','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10016,1,'Paul','16','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10017,1,'Jane','17','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10018,1,'Marry','18','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10019,1,'Ben','19','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10020,1,'Bot','20','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10021,1,'Jack','21','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10022,1,'Martin','22','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10023,1,'Alex','23','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10024,1,'Daniel','24','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10025,1,'Eric','25','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10026,1,'Leon','26','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10027,1,'Clark','27','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10028,1,'David','28','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10029,1,'Henry','29','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10030,1,'Helen','30','1');
INSERT INTO PARTY_ENTITY(ID,TYPE_ID,NAME,REF,TENANT_ID) VALUES(10031,1,'Sarah','31','1');

-- 公司下面加上行政部
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(201,1,1,30011,'1');
-- 市场部下面加上销售部和客服部
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(202,1,2,30012,'1');
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(203,1,2,30013,'1');
-- robot, bob, alice加到行政部
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(301,1,30011,10008,'1');
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(302,1,30011,10009,'1');
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(303,1,30011,10010,'1');
-- mike, justin, tom加入销售部
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(304,1,30012,10011,'1');
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(305,1,30012,10012,'1');
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(306,1,30012,10013,'1');
-- james, joe, paul加入客服部
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(307,1,30013,10014,'1');
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(308,1,30013,10015,'1');
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(309,1,30013,10016,'1');
-- jane, marry加入公司
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(310,1,1,10017,'1');
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(311,1,1,10018,'1');
-- ben, jack加入市场部
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(312,1,2,10019,'1');
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(313,1,2,10021,'1');
-- martin, alex加入财务部
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(314,1,3,10022,'1');
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(315,1,3,10023,'1');
-- daniel, eric加入人事部
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(316,1,4,10024,'1');
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(317,1,4,10025,'1');
-- leon, clark加入研发部
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(318,1,5,10026,'1');
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(319,1,5,10027,'1');
-- david, henry加入平台组
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(320,1,6,10028,'1');
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(321,1,6,10029,'1');
-- helen, sarah加入OA组
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(322,1,7,10030,'1');
INSERT INTO PARTY_STRUCT(ID,STRUCT_TYPE_ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,TENANT_ID) VALUES(323,1,7,10031,'1');


