

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"申请单"},{"type":"grid","row":"2","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"请假原因"},{"type":"label","row":1,"col":0,"text":"请假类型"},{"type":"textfield","row":0,"col":1,"name":"reason","required":false,"readOnly":false},{"type":"radio","row":1,"col":1,"name":"type","items":"倒休,事假,病假,婚假","required":false,"readOnly":false}]}]}' where ID=1;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"上级审批"},{"type":"grid","row":"3","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3},{"startId":"2-1","minRow":2,"minCol":1,"maxRow":2,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"请假原因"},{"type":"label","row":1,"col":0,"text":"请假类型"},{"type":"textfield","row":0,"col":1,"name":"reason","required":false,"readOnly":true},{"type":"radio","row":1,"col":1,"name":"type","items":"倒休,事假,病假,婚假","required":false,"readOnly":true},{"type":"label","row":2,"col":0,"text":"部门经理意见"},{"type":"radio","row":2,"col":1,"name":"leaderComment","items":"同意,不同意","required":false,"readOnly":false}]}]}' where ID=2;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"人事审批"},{"type":"grid","row":"4","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3},{"startId":"2-1","minRow":2,"minCol":1,"maxRow":2,"maxCol":3},{"startId":"3-1","minRow":3,"minCol":1,"maxRow":3,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"请假原因"},{"type":"label","row":1,"col":0,"text":"请假类型"},{"type":"textfield","row":0,"col":1,"name":"reason","required":false,"readOnly":true},{"type":"radio","row":1,"col":1,"name":"type","items":"倒休,事假,病假,婚假","required":false,"readOnly":true},{"type":"label","row":2,"col":0,"text":"部门经理意见"},{"type":"radio","row":2,"col":1,"name":"leaderComment","items":"同意,不同意","required":false,"readOnly":true},{"type":"label","row":3,"col":0,"text":"人事意见"},{"type":"radio","row":3,"col":1,"name":"hrComment","items":"同意,不同意","required":false,"readOnly":false}]}]}' where ID=3;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"调整申请"},{"type":"grid","row":"3","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3},{"startId":"2-1","minRow":2,"minCol":1,"maxRow":2,"maxCol":3},{"startId":"3-1","minRow":3,"minCol":1,"maxRow":3,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"请假原因"},{"type":"label","row":1,"col":0,"text":"请假类型"},{"type":"textfield","row":0,"col":1,"name":"reason","required":false,"readOnly":false},{"type":"radio","row":1,"col":1,"name":"type","items":"倒休,事假,病假,婚假","required":false,"readOnly":false},{"type":"label","row":2,"col":0,"text":"调整申请"},{"type":"radio","row":2,"col":1,"name":"initiatorComment","items":"重新申请,撤销申请","required":false,"readOnly":false}]}]}' where ID=4;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"人事审批"},{"type":"grid","row":"4","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3},{"startId":"2-1","minRow":2,"minCol":1,"maxRow":2,"maxCol":3},{"startId":"3-1","minRow":3,"minCol":1,"maxRow":3,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"请假原因"},{"type":"label","row":1,"col":0,"text":"请假类型"},{"type":"textfield","row":0,"col":1,"name":"reason","required":false,"readOnly":true},{"type":"radio","row":1,"col":1,"name":"type","items":"倒休,事假,病假,婚假","required":false,"readOnly":true},{"type":"label","row":2,"col":0,"text":"部门经理意见"},{"type":"radio","row":2,"col":1,"name":"leaderComment","items":"同意,不同意","required":false,"readOnly":true},{"type":"label","row":3,"col":0,"text":"人事意见"},{"type":"radio","row":3,"col":1,"name":"hrComment","items":"同意,不同意","required":false,"readOnly":true}]}]}' where ID=5;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"发文"},{"type":"grid","row":"3","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3},{"startId":"2-1","minRow":2,"minCol":1,"maxRow":2,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"标题"},{"type":"textfield","row":0,"col":1,"name":"title","required":false,"readOnly":false},{"type":"textarea","row":2,"col":1,"name":"content","required":false,"readOnly":false},{"type":"label","row":2,"col":0,"text":"内容"},{"type":"label","row":1,"col":0,"text":"拟稿审批"},{"type":"userpicker","row":1,"col":1,"name":"countersignUsers","required":false,"readOnly":false}]}]}' where ID=6;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"经理审批"},{"type":"grid","row":"3","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3},{"startId":"2-1","minRow":2,"minCol":1,"maxRow":2,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"标题"},{"type":"textfield","row":0,"col":1,"name":"title","required":false,"readOnly":true},{"type":"radio","row":2,"col":1,"name":"leaderComment","items":"同意,不同意","required":false,"readOnly":false},{"type":"label","row":2,"col":0,"text":"部门经理意见"},{"type":"label","row":1,"col":0,"text":"内容"},{"type":"textarea","row":1,"col":1,"name":"content","required":false,"readOnly":true}]}]}' where ID=7;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"会签审批"},{"type":"grid","row":"3","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3},{"startId":"2-1","minRow":2,"minCol":1,"maxRow":2,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"标题"},{"type":"textfield","row":0,"col":1,"name":"title","required":false,"readOnly":true},{"type":"radio","row":2,"col":1,"name":"countersignComment","items":"同意,不同意","required":false,"readOnly":false},{"type":"label","row":2,"col":0,"text":"审批意见"},{"type":"label","row":1,"col":0,"text":"内容"},{"type":"textarea","row":1,"col":1,"name":"content","required":false,"readOnly":true}]}]}' where ID=8;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"归档"},{"type":"grid","row":"2","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"标题"},{"type":"textfield","row":0,"col":1,"name":"title","required":false,"readOnly":true},{"type":"textarea","row":1,"col":1,"name":"content","required":false,"readOnly":true},{"type":"label","row":1,"col":0,"text":"内容"}]}]}' where ID=9;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"permission发起申请"},{"type":"grid","row":"1","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"申请"},{"type":"textfield","row":0,"col":1,"name":"name","required":false,"readOnly":false}]}]}' where ID=10;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"permission经理审批"},{"type":"grid","row":"2","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"申请"},{"type":"textfield","row":0,"col":1,"name":"name","required":false,"readOnly":true},{"type":"label","row":1,"col":0,"text":"经理审批意见"},{"type":"radio","row":1,"col":1,"name":"managerComment","items":"同意,不同意","required":false,"readOnly":false}]}]}' where ID=11;

UPDATE FORM_TEMPLATE SET CONTENT='{"sections":[{"type":"text","tag":"h1","text":"permission模块负责人审批"},{"type":"grid","row":"3","col":"4","merge":[{"startId":"0-1","minRow":0,"minCol":1,"maxRow":0,"maxCol":3},{"startId":"1-1","minRow":1,"minCol":1,"maxRow":1,"maxCol":3},{"startId":"2-1","minRow":2,"minCol":1,"maxRow":2,"maxCol":3}],"fields":[{"type":"label","row":0,"col":0,"text":"申请"},{"type":"textfield","row":0,"col":1,"name":"name","required":false,"readOnly":true},{"type":"label","row":1,"col":0,"text":"经理审批意见"},{"type":"radio","row":1,"col":1,"name":"managerComment","items":"同意,不同意","required":false,"readOnly":true},{"type":"label","row":2,"col":0,"text":"模块负责人审批意见"},{"type":"radio","row":2,"col":1,"name":"leaderComment","items":"同意,不同意","required":false,"readOnly":false}]}]}' where ID=12;

