

ALTER TABLE SYS_INFO ADD COLUMN APP_KEY VARCHAR(200);
ALTER TABLE SYS_INFO ADD COLUMN APP_SECRET VARCHAR(200);
ALTER TABLE SYS_INFO ADD COLUMN APP_URL VARCHAR(200);
ALTER TABLE SYS_INFO ADD COLUMN PC_URL VARCHAR(200);
ALTER TABLE SYS_INFO ADD COLUMN ADMIN_URL VARCHAR(200);

COMMENT ON COLUMN SYS_INFO.APP_KEY IS 'app key';
COMMENT ON COLUMN SYS_INFO.APP_SECRET IS 'app secret';
COMMENT ON COLUMN SYS_INFO.APP_URL IS '移动端网址';
COMMENT ON COLUMN SYS_INFO.PC_URL IS 'PC端网址';
COMMENT ON COLUMN SYS_INFO.ADMIN_URL IS '管理端网址';

