

ALTER TABLE OPEN_APP ADD COLUMN LOGO VARCHAR(200);
ALTER TABLE OPEN_APP ADD COLUMN USERGUIDE VARCHAR(200);
ALTER TABLE OPEN_APP ADD COLUMN ADMIN_URL VARCHAR(200);
ALTER TABLE OPEN_APP ADD COLUMN LANGUAGE VARCHAR(100);
ALTER TABLE OPEN_APP ADD COLUMN VERSION_NO VARCHAR(10);
ALTER TABLE OPEN_APP ADD COLUMN DEVELOPER_NAME VARCHAR(50);
ALTER TABLE OPEN_APP ADD COLUMN DEVELOPER_USER_ID VARCHAR(50);
ALTER TABLE OPEN_APP ADD COLUMN CATEGORY_ID BIGINT;

ALTER TABLE OPEN_APP ADD FOREIGN KEY (CATEGORY_ID) REFERENCES OPEN_CATEGORY(ID);

COMMENT ON COLUMN OPEN_APP.LOGO IS '图标';
COMMENT ON COLUMN OPEN_APP.USERGUIDE IS '帮助文档';
COMMENT ON COLUMN OPEN_APP.ADMIN_URL IS '管理后台网址';
COMMENT ON COLUMN OPEN_APP.LANGUAGE IS '语言';
COMMENT ON COLUMN OPEN_APP.VERSION_NO IS '版本号';
COMMENT ON COLUMN OPEN_APP.DEVELOPER_NAME IS '开发者名称';
COMMENT ON COLUMN OPEN_APP.DEVELOPER_USER_ID IS '开发者联系人';
COMMENT ON COLUMN OPEN_APP.CATEGORY_ID IS '分类';

