

-------------------------------------------------------------------------------
--  stamp info
-------------------------------------------------------------------------------
CREATE TABLE STAMP_INFO(
    ID BIGINT NOT NULL,
    COMPANY_NAME VARCHAR(100),
    NAME VARCHAR(200),
    TYPE VARCHAR(50),
    USER_ID VARCHAR(64),
    STATUS VARCHAR(50),
    DESCRIPTION VARCHAR(200),
    TENANT_ID VARCHAR(64),
    CONSTRAINT PK_STAMP_INFO PRIMARY KEY(ID)
);

COMMENT ON TABLE STAMP_INFO IS '印章';
COMMENT ON COLUMN STAMP_INFO.ID IS '主键';
COMMENT ON COLUMN STAMP_INFO.COMPANY_NAME IS '公司';
COMMENT ON COLUMN STAMP_INFO.NAME IS '名称';
COMMENT ON COLUMN STAMP_INFO.TYPE IS '类型';
COMMENT ON COLUMN STAMP_INFO.USER_ID IS '保管人';
COMMENT ON COLUMN STAMP_INFO.STATUS IS '状态';
COMMENT ON COLUMN STAMP_INFO.DESCRIPTION IS '备注';
COMMENT ON COLUMN STAMP_INFO.TENANT_ID IS '租户';

