

-------------------------------------------------------------------------------
--  user status
-------------------------------------------------------------------------------
CREATE TABLE AUTH_USER_STATUS(
        ID BIGINT NOT NULL,
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50),
	STATUS INTEGER,
	REFERENCE VARCHAR(200),
	USER_REPO_REF VARCHAR(50),
	SCOPE_ID VARCHAR(50),
	CONSTRAINT PK_AUTH_USER_STATUS PRIMARY KEY(ID)
);

COMMENT ON TABLE AUTH_USER_STATUS IS '账号';
COMMENT ON COLUMN AUTH_USER_STATUS.ID IS '主键';
COMMENT ON COLUMN AUTH_USER_STATUS.USERNAME IS '账号';
COMMENT ON COLUMN AUTH_USER_STATUS.PASSWORD IS '遗留字段';
COMMENT ON COLUMN AUTH_USER_STATUS.STATUS IS '状态';
COMMENT ON COLUMN AUTH_USER_STATUS.REFERENCE IS '外部引用';
COMMENT ON COLUMN AUTH_USER_STATUS.USER_REPO_REF IS '账号体系引用，暂时没用';
COMMENT ON COLUMN AUTH_USER_STATUS.SCOPE_ID IS '租户';
