

-------------------------------------------------------------------------------
--  resc
-------------------------------------------------------------------------------
CREATE TABLE AUTH_RESC(
        ID BIGINT NOT NULL,
	TYPE VARCHAR(50),
	CODE VARCHAR(50),
	TITLE VARCHAR(50),
	URL VARCHAR(200),
	ICON VARCHAR(100),
	PRIORITY INTEGER,
	DESCN VARCHAR(200),
	STATUS VARCHAR(50),
	DISPLAY VARCHAR(50),
	PARENT_ID BIGINT,
	PERM_ID BIGINT,

	TENANT_ID VARCHAR(64),

	CONSTRAINT PK_AUTH_RESC PRIMARY KEY(ID),
	CONSTRAINT FK_AUTH_RESC_PARENT FOREIGN KEY(PARENT_ID) REFERENCES AUTH_RESC(ID),
	CONSTRAINT FK_AUTH_RESC_PERM FOREIGN KEY(PERM_ID) REFERENCES AUTH_PERM(ID)
);

COMMENT ON TABLE AUTH_RESC IS '资源';
COMMENT ON COLUMN AUTH_RESC.ID IS '主键';
COMMENT ON COLUMN AUTH_RESC.TYPE IS '分类';
COMMENT ON COLUMN AUTH_RESC.CODE IS '编码';
COMMENT ON COLUMN AUTH_RESC.TITLE IS '标题';
COMMENT ON COLUMN AUTH_RESC.URL IS '链接';
COMMENT ON COLUMN AUTH_RESC.ICON IS '图标';
COMMENT ON COLUMN AUTH_RESC.PRIORITY IS '排序';
COMMENT ON COLUMN AUTH_RESC.DESCN IS '备注';
COMMENT ON COLUMN AUTH_RESC.STATUS IS '状态';
COMMENT ON COLUMN AUTH_RESC.DISPLAY IS '显示';
COMMENT ON COLUMN AUTH_RESC.PARENT_ID IS '外键，上级菜单';
COMMENT ON COLUMN AUTH_RESC.PERM_ID IS '外键，权限';
COMMENT ON COLUMN AUTH_RESC.TENANT_ID IS '租户';
