
ALTER TABLE AUTH_ACCESS ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;
ALTER TABLE AUTH_PERM ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;
ALTER TABLE AUTH_PERM_TYPE ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;
ALTER TABLE AUTH_ROLE ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;
ALTER TABLE AUTH_ROLE_DEF ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;
ALTER TABLE AUTH_USER_STATUS ALTER COLUMN SCOPE_ID RENAME TO TENANT_ID;

