
ALTER TABLE AUTH_PERM ADD COLUMN PARENT_ID BIGINT;
ALTER TABLE AUTH_PERM ADD COLUMN TYPE VARCHAR(50);
ALTER TABLE AUTH_PERM ADD COLUMN TITLE VARCHAR(50);
ALTER TABLE AUTH_PERM ADD COLUMN URL VARCHAR(200);
ALTER TABLE AUTH_PERM ADD COLUMN ICON VARCHAR(50);

ALTER TABLE AUTH_PERM ADD CONSTRAINT FK_AUTH_PERM_PARENT FOREIGN KEY(PARENT_ID) REFERENCES AUTH_PERM(ID);

