

-------------------------------------------------------------------------------
--  user status
-------------------------------------------------------------------------------
CREATE TABLE AUTH_USER_STATUS(
	ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
	USERNAME VARCHAR(50),
	PASSWORD VARCHAR(50),
	STATUS INTEGER,
	REFERENCE VARCHAR(200),
	DESCN VARCHAR(200),
	GLOBAL_ID BIGINT,
	LOCAL_ID BIGINT,
	CONSTRAINT PK_AUTH_USER_STATUS PRIMARY KEY(ID)
);
