package com.mossle.plm.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PlmProduct 需求.
 * 
 * @author Lingo
 */
@Entity
@Table(name = "PLM_PRODUCT")
public class PlmProduct implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** 主键. */
    private Long id;

    /** null. */
    private String code;

    /** null. */
    private String name;

    /** null. */
    private String category;

    /** null. */
    private String severity;

    /** null. */
    private Integer priority;

    /** null. */
    private String type;

    /** null. */
    private Date deadline;

    /** null. */
    private String description;

    /** null. */
    private String tag;

    /** null. */
    private String status;

    /** null. */
    private Date createTime;

    /** null. */
    private String userId;

    /** null. */
    private Long parentId;

    /** null. */
    private Long issueId;

    /** null. */
    private Long versionId;

    /** null. */
    private Long projectId;

    /** null. */
    private String groupName;

    /** null. */
    private String assignee;

    public PlmProduct() {
    }

    public PlmProduct(Long id) {
        this.id = id;
    }

    public PlmProduct(Long id, String code, String name, String category,
            String severity, Integer priority, String type, Date deadline,
            String description, String tag, String status, Date createTime,
            String userId, Long parentId, Long issueId, Long versionId,
            Long projectId, String groupName, String assignee) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.category = category;
        this.severity = severity;
        this.priority = priority;
        this.type = type;
        this.deadline = deadline;
        this.description = description;
        this.tag = tag;
        this.status = status;
        this.createTime = createTime;
        this.userId = userId;
        this.parentId = parentId;
        this.issueId = issueId;
        this.versionId = versionId;
        this.projectId = projectId;
        this.groupName = groupName;
        this.assignee = assignee;
    }

    /** @return 主键. */
    @Id
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            主键.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @Column(name = "CODE", length = 50)
    public String getCode() {
        return this.code;
    }

    /**
     * @param code
     *            null.
     */
    public void setCode(String code) {
        this.code = code;
    }

    /** @return null. */
    @Column(name = "NAME", length = 200)
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            null.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** @return null. */
    @Column(name = "CATEGORY", length = 50)
    public String getCategory() {
        return this.category;
    }

    /**
     * @param category
     *            null.
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /** @return null. */
    @Column(name = "SEVERITY", length = 50)
    public String getSeverity() {
        return this.severity;
    }

    /**
     * @param severity
     *            null.
     */
    public void setSeverity(String severity) {
        this.severity = severity;
    }

    /** @return null. */
    @Column(name = "PRIORITY")
    public Integer getPriority() {
        return this.priority;
    }

    /**
     * @param priority
     *            null.
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /** @return null. */
    @Column(name = "TYPE", length = 50)
    public String getType() {
        return this.type;
    }

    /**
     * @param type
     *            null.
     */
    public void setType(String type) {
        this.type = type;
    }

    /** @return null. */
    @Temporal(TemporalType.DATE)
    @Column(name = "DEADLINE", length = 10)
    public Date getDeadline() {
        return this.deadline;
    }

    /**
     * @param deadline
     *            null.
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /** @return null. */
    @Column(name = "DESCRIPTION", length = 200)
    public String getDescription() {
        return this.description;
    }

    /**
     * @param description
     *            null.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /** @return null. */
    @Column(name = "TAG", length = 200)
    public String getTag() {
        return this.tag;
    }

    /**
     * @param tag
     *            null.
     */
    public void setTag(String tag) {
        this.tag = tag;
    }

    /** @return null. */
    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    /**
     * @param status
     *            null.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /** @return null. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_TIME", length = 26)
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * @param createTime
     *            null.
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /** @return null. */
    @Column(name = "USER_ID", length = 64)
    public String getUserId() {
        return this.userId;
    }

    /**
     * @param userId
     *            null.
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /** @return null. */
    @Column(name = "PARENT_ID")
    public Long getParentId() {
        return this.parentId;
    }

    /**
     * @param parentId
     *            null.
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /** @return null. */
    @Column(name = "ISSUE_ID")
    public Long getIssueId() {
        return this.issueId;
    }

    /**
     * @param issueId
     *            null.
     */
    public void setIssueId(Long issueId) {
        this.issueId = issueId;
    }

    /** @return null. */
    @Column(name = "VERSION_ID")
    public Long getVersionId() {
        return this.versionId;
    }

    /**
     * @param versionId
     *            null.
     */
    public void setVersionId(Long versionId) {
        this.versionId = versionId;
    }

    /** @return null. */
    @Column(name = "PROJECT_ID")
    public Long getProjectId() {
        return this.projectId;
    }

    /**
     * @param projectId
     *            null.
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /** @return null. */
    @Column(name = "GROUP_NAME", length = 200)
    public String getGroupName() {
        return this.groupName;
    }

    /**
     * @param groupName
     *            null.
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /** @return null. */
    @Column(name = "ASSIGNEE", length = 64)
    public String getAssignee() {
        return this.assignee;
    }

    /**
     * @param assignee
     *            null.
     */
    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }
}
