
INSERT INTO BPM_CONF_BASE(ID,PROCESS_DEFINITION_KEY,PROCESS_DEFINITION_VERSION) VALUES(1,'vacation',1);

INSERT INTO BPM_CONF_BASE(ID,PROCESS_DEFINITION_KEY,PROCESS_DEFINITION_VERSION) VALUES(2,'publish',1);

INSERT INTO BPM_CONF_BASE(ID,PROCESS_DEFINITION_KEY,PROCESS_DEFINITION_VERSION) VALUES(3,'permission',1);

UPDATE BPM_PROCESS SET CONF_BASE_ID=1 WHERE ID=1;

UPDATE BPM_PROCESS SET CONF_BASE_ID=2 WHERE ID=2;

UPDATE BPM_PROCESS SET CONF_BASE_ID=3 WHERE ID=3;

UPDATE BPM_PROCESS SET CODE='vacation' WHERE ID=1;

UPDATE BPM_PROCESS SET CODE='publish' WHERE ID=2;

UPDATE BPM_PROCESS SET CODE='permission' WHERE ID=3;

