
INSERT INTO BPM_CATEGORY(ID,NAME,PRIORITY,TENANT_ID) VALUES(2,'行政',2,1);
INSERT INTO BPM_CATEGORY(ID,NAME,PRIORITY,TENANT_ID) VALUES(3,'人事',3,1);
INSERT INTO BPM_CATEGORY(ID,NAME,PRIORITY,TENANT_ID) VALUES(4,'财务',4,1);

INSERT INTO BPM_CONF_BASE(ID,PROCESS_DEFINITION_KEY,PROCESS_DEFINITION_VERSION) VALUES(4,'travel',1);
INSERT INTO BPM_CONF_BASE(ID,PROCESS_DEFINITION_KEY,PROCESS_DEFINITION_VERSION) VALUES(5,'expense',1);
INSERT INTO BPM_CONF_BASE(ID,PROCESS_DEFINITION_KEY,PROCESS_DEFINITION_VERSION) VALUES(6,'asset',1);
INSERT INTO BPM_CONF_BASE(ID,PROCESS_DEFINITION_KEY,PROCESS_DEFINITION_VERSION) VALUES(7,'stamp',1);
INSERT INTO BPM_CONF_BASE(ID,PROCESS_DEFINITION_KEY,PROCESS_DEFINITION_VERSION) VALUES(8,'fee',1);

INSERT INTO BPM_PROCESS(ID,CODE,NAME,PRIORITY,DESCN,CATEGORY_ID,USE_TASK_CONF,CONF_BASE_ID,TENANT_ID) VALUES(4,'travel', '差旅审批',4,'差旅审批',3,0,4,1);
INSERT INTO BPM_PROCESS(ID,CODE,NAME,PRIORITY,DESCN,CATEGORY_ID,USE_TASK_CONF,CONF_BASE_ID,TENANT_ID) VALUES(5,'expense','报销审批',5,'报销审批',4,0,5,1);
INSERT INTO BPM_PROCESS(ID,CODE,NAME,PRIORITY,DESCN,CATEGORY_ID,USE_TASK_CONF,CONF_BASE_ID,TENANT_ID) VALUES(6,'asset',  '资产审批',6,'资产审批',2,0,6,1);
INSERT INTO BPM_PROCESS(ID,CODE,NAME,PRIORITY,DESCN,CATEGORY_ID,USE_TASK_CONF,CONF_BASE_ID,TENANT_ID) VALUES(7,'stamp',  '印章审批',7,'印章审批',2,0,7,1);
INSERT INTO BPM_PROCESS(ID,CODE,NAME,PRIORITY,DESCN,CATEGORY_ID,USE_TASK_CONF,CONF_BASE_ID,TENANT_ID) VALUES(8,'fee',    '费用审批',8,'费用审批',4,0,8,1);

