

-------------------------------------------------------------------------------
--  whitelist info
-------------------------------------------------------------------------------
CREATE TABLE WHITELIST_INFO(
        ID BIGINT NOT NULL,
	CODE VARCHAR(50),
	NAME VARCHAR(50),
	USER_ID VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	CREATE_TIME DATETIME,
	UPDATE_TIME DATETIME,
	STATUS VARCHAR(50),

	APP_ID BIGINT,
	SERVICE_ID BIGINT,

        CONSTRAINT PK_WHITELIST_INFO PRIMARY KEY(ID),
        CONSTRAINT FK_WHITELIST_INFO_APP FOREIGN KEY(APP_ID) REFERENCES WHITELIST_APP(ID),
        CONSTRAINT FK_WHITELIST_INFO_SERVICE FOREIGN KEY(SERVICE_ID) REFERENCES WHITELIST_SERVICE(ID)
) ENGINE=INNODB CHARSET=UTF8;

