

-------------------------------------------------------------------------------
--  resc
-------------------------------------------------------------------------------
CREATE TABLE AUTH_RESC(
        ID BIGINT NOT NULL,
	TYPE VARCHAR(50),
	CODE VARCHAR(50),
	TITLE VARCHAR(50),
	URL VARCHAR(200),
	ICON VARCHAR(100),
	PRIORITY INTEGER,
	DESCN VARCHAR(200),
	STATUS VARCHAR(50),
	DISPLAY VARCHAR(50),
	PARENT_ID BIGINT,
	PERM_ID BIGINT,

	TENANT_ID VARCHAR(64),

	CONSTRAINT PK_AUTH_RESC PRIMARY KEY(ID),
	CONSTRAINT FK_AUTH_RESC_PARENT FOREIGN KEY(PARENT_ID) REFERENCES AUTH_RESC(ID),
	CONSTRAINT FK_AUTH_RESC_PERM FOREIGN KEY(PERM_ID) REFERENCES AUTH_PERM(ID)
) ENGINE=INNODB CHARSET=UTF8;















