package com.mossle.form.domain;

// Generated by Hibernate Tools
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DynamicModel .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "M_DYNAMIC_MODEL")
public class DynamicModel implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private String type;

    /** null. */
    private String definitionId;

    /** null. */
    private String instanceId;

    /** null. */
    private String executionId;

    /** null. */
    private Integer status;

    /** . */
    private Set<DynamicModelData> dynamicModelDatas = new HashSet<DynamicModelData>(
            0);

    public DynamicModel() {
    }

    public DynamicModel(String type, String definitionId, String instanceId,
            String executionId, Integer status,
            Set<DynamicModelData> dynamicModelDatas) {
        this.type = type;
        this.definitionId = definitionId;
        this.instanceId = instanceId;
        this.executionId = executionId;
        this.status = status;
        this.dynamicModelDatas = dynamicModelDatas;
    }

    /** @return null. */
    @Id
    @GeneratedValue
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @Column(name = "TYPE", length = 200)
    public String getType() {
        return this.type;
    }

    /**
     * @param type
     *            null.
     */
    public void setType(String type) {
        this.type = type;
    }

    /** @return null. */
    @Column(name = "DEFINITION_ID", length = 200)
    public String getDefinitionId() {
        return this.definitionId;
    }

    /**
     * @param definitionId
     *            null.
     */
    public void setDefinitionId(String definitionId) {
        this.definitionId = definitionId;
    }

    /** @return null. */
    @Column(name = "INSTANCE_ID", length = 200)
    public String getInstanceId() {
        return this.instanceId;
    }

    /**
     * @param instanceId
     *            null.
     */
    public void setInstanceId(String instanceId) {
        this.instanceId = instanceId;
    }

    /** @return null. */
    @Column(name = "EXECUTION_ID", length = 200)
    public String getExecutionId() {
        return this.executionId;
    }

    /**
     * @param executionId
     *            null.
     */
    public void setExecutionId(String executionId) {
        this.executionId = executionId;
    }

    /** @return null. */
    @Column(name = "STATUS")
    public Integer getStatus() {
        return this.status;
    }

    /**
     * @param status
     *            null.
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /** @return . */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "dynamicModel")
    public Set<DynamicModelData> getDynamicModelDatas() {
        return this.dynamicModelDatas;
    }

    /**
     * @param dynamicModelDatas
     *            .
     */
    public void setDynamicModelDatas(Set<DynamicModelData> dynamicModelDatas) {
        this.dynamicModelDatas = dynamicModelDatas;
    }
}
