

INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(11,'PARENT','全局配置',1,1,1);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(12,'FRONTEND','前端框架',2,1,1);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(13,'BACKEND','后端框架',3,1,1);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(14,'TEST','测试工具',4,1,1);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(15,'CORE','核心工具',5,1,1);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(16,'SECURITY','权限控制',6,1,1);

INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(21,'DICT','数据字典',1,1,2);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(22,'MAIL','邮件',2,1,2);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(23,'STORE','附件',3,1,2);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(24,'TEMPLATE','模板',4,1,2);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(25,'WHITELIST','白名单',5,1,2);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(26,'WORKCAL','工作日历',6,1,2);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(27,'AUDIT','审计日志',7,1,2);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(28,'ONLINE','在线列表',8,1,2);

INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(31,'USER','用户管理',1,1,3);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(32,'ORG','组织机构',2,1,3);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(33,'AUTH','权限控制',3,1,3);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(34,'FORM','电子表单',4,1,3);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(35,'TASK','任务中心',5,1,3);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(36,'BPM','业务流程',6,1,3);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(37,'OPERATION','操作',7,1,3);

INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(41,'PIM','个人事务',1,1,4);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(42,'LOGISTIC','行政管理',2,1,4);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(43,'LEMON','LemonOA',3,1,4);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(44,'PLM','项目追踪',4,1,4);

INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(51,'NEWS','新闻',1,1,5);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(52,'FORUM','论坛',2,1,5);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(53,'WIKI','WIKI',3,1,5);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(54,'ASK','问答',4,1,5);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(55,'MSG','站内信',5,1,5);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(56,'SNS','互动',6,1,5);

INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(9901,'TENANT','多租户',1,1,99);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(9902,'ACL','数据权限',2,1,99);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(9903,'REPORT','报表管理',3,1,99);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(9904,'EXPORT','导出管理',4,1,99);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(9905,'DEV','研发管理',5,1,99);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(9906,'HR','人事管理',6,1,99);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(9907,'APP','移动端',7,1,99);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(9908,'IM','即时通讯',8,1,99);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(9909,'DEEP','深度学习',9,1,99);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(9910,'JAVAMAIL','邮件客户端',10,1,99);
INSERT INTO PLM_PROJECT(ID,CODE,NAME,PRIORITY,LEADER_ID,CATEGORY_ID) VALUES(9911,'SMS','短信',11,1,99);

