

ALTER TABLE ACCOUNT_INFO ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE ACCOUNT_CREDENTIAL ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE PERSON_INFO ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE ACCOUNT_AVATAR ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE ACCOUNT_ONLINE ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE ACCOUNT_LOCK_INFO ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE ACCOUNT_LOCK_LOG ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE ACCOUNT_LOG ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE ACCOUNT_HISTORY_CREDENTIAL ADD COLUMN TENANT_ID VARCHAR(64);












