

INSERT INTO ACL_SID(ID,NAME,REFERENCE,GLOBAL_ID,LOCAL_ID) VALUES(1,'Lingo',1,1,1);
INSERT INTO ACL_SID(ID,NAME,REFERENCE,GLOBAL_ID,LOCAL_ID) VALUES(2,'Vivian',2,1,1);

INSERT INTO ACL_OBJECT_TYPE(ID,CODE,NAME,GLOBAL_ID,LOCAL_ID) VALUES(1,'course','课程',1,1);

INSERT INTO ACL_OBJECT_IDENTITY(ID,REFERENCE,ENTRIES_HIERITING,OBJECT_TYPE_ID,OWNER_ID,PARENT_ID,GLOBAL_ID,LOCAL_ID) VALUES(1,'1',0,1,1,NULL,1,1);

INSERT INTO ACL_ENTRY(ID,ACE_ORDER,GRANTING,AUDIT_SUCCESS,AUDIT_FAILURE,MASK,OBJECT_IDENTITY_ID,SID_ID,GLOBAL_ID,LOCAL_ID) VALUES(1,1,1,0,0,1,1,1,1,1);

