

-------------------------------------------------------------------------------
--  humantask
-------------------------------------------------------------------------------
CREATE TABLE HT_HUMANTASK(
	ID BIGINT NOT NULL,
	NAME VARCHAR(200),
	DESCRIPTION VARCHAR(200),
	ASSIGNEE VARCHAR(64),
	OWNER VARCHAR(64),
	DELEGATE_STATUS VARCHAR(50),
	PRIORITY INT,
	CREATE_TIME DATETIME,
	DURATION VARCHAR(50),
	SUSPEND_STATUS VARCHAR(50),
	CATEGORY VARCHAR(50),
	CODE VARCHAR(200),
	FORM VARCHAR(200),
	TASK_ID VARCHAR(200),
	EXECUTION_ID VARCHAR(200),
	PROCESS_INSTANCE_ID VARCHAR(200),
	PROCESS_DEFINITION_ID VARCHAR(200),
	TENENT_ID VARCHAR(64),
	PARENT_ID BIGINT,
	STATUS VARCHAR(50),
	COMPLETE_TIME DATETIME,
        CONSTRAINT PK_HT_HUMANTASK PRIMARY KEY(ID),
	CONSTRAINT FK_HT_HUMANTASK_PARENT FOREIGN KEY(PARENT_ID) REFERENCES HT_HUMANTASK(ID)
) ENGINE=INNODB CHARSET=UTF8;




























