

-------------------------------------------------------------------------------
--  task def deadline
-------------------------------------------------------------------------------
CREATE TABLE TASK_DEF_DEADLINE(
	ID BIGINT NOT NULL,
	TYPE VARCHAR(50),
	DURATION VARCHAR(100),
	STATUS VARCHAR(50),
	ESCALATION_TYPE VARCHAR(50),
	NOTIFICATION_CONDITION VARCHAR(200),
	NOTIFICATION_TYPE VARCHAR(200),
	NOTIFICATION_RECEIVER VARCHAR(200),
	NOTIFICATION_TEMPLATE_CODE VARCHAR(200),
	REASSGINMENT VARCHAR(200),
	OPERATION VARCHAR(200),
	BASE_ID BIGINT,
        CONSTRAINT PK_TASK_DEF_DEADLINE PRIMARY KEY(ID),
        CONSTRAINT FK_TASK_DEF_DEADLINE_BASE FOREIGN KEY(BASE_ID) REFERENCES TASK_DEF_BASE(ID)
) ENGINE=INNODB CHARSET=UTF8;
















