

ALTER TABLE TASK_INFO ADD COLUMN PROCESS_STARTER VARCHAR(64);


ALTER TABLE TASK_INFO ADD COLUMN CATALOG VARCHAR(100);


ALTER TABLE TASK_INFO ADD COLUMN ACTION VARCHAR(200);


ALTER TABLE TASK_INFO ADD COLUMN COMMENT VARCHAR(200);


ALTER TABLE TASK_INFO ADD COLUMN MESSAGE VARCHAR(200);


