
UPDATE JOB_GRADE set PRIORITY=1 where id=1;
UPDATE JOB_GRADE set PRIORITY=2 where id=2;

UPDATE JOB_LEVEL set PRIORITY=1 where id=1;
UPDATE JOB_LEVEL set PRIORITY=2 where id=2;
UPDATE JOB_LEVEL set PRIORITY=3 where id=3;
