

INSERT INTO GROUP_TYPE(ID,NAME,TENANT_ID) VALUES(1,'default',1);

INSERT INTO GROUP_INFO(ID,NAME,MEMBER_COUNT,TENANT_ID) VALUES(1,'全体成员',8,1);

INSERT INTO GROUP_ADMIN(ID,INFO_ID,USER_ID,TENANT_ID) VALUES(1,1,1,1);

INSERT INTO GROUP_MEMBER(ID,INFO_ID,USER_ID,TENANT_ID) VALUES(1,1,1,1);
INSERT INTO GROUP_MEMBER(ID,INFO_ID,USER_ID,TENANT_ID) VALUES(2,1,2,1);
INSERT INTO GROUP_MEMBER(ID,INFO_ID,USER_ID,TENANT_ID) VALUES(3,1,3,1);
INSERT INTO GROUP_MEMBER(ID,INFO_ID,USER_ID,TENANT_ID) VALUES(4,1,4,1);
INSERT INTO GROUP_MEMBER(ID,INFO_ID,USER_ID,TENANT_ID) VALUES(5,1,5,1);
INSERT INTO GROUP_MEMBER(ID,INFO_ID,USER_ID,TENANT_ID) VALUES(6,1,6,1);
INSERT INTO GROUP_MEMBER(ID,INFO_ID,USER_ID,TENANT_ID) VALUES(7,1,7,1);
INSERT INTO GROUP_MEMBER(ID,INFO_ID,USER_ID,TENANT_ID) VALUES(8,1,8,1);

