

INSERT INTO BPM_CATEGORY(ID,NAME,PRIORITY) VALUES(1,'常用流程',1);

INSERT INTO BPM_PROCESS(ID,NAME,PRIORITY,DESCN,CATEGORY_ID,PROCESS_DEFINITION_ID,PROCESS_DEFINITION_KEY,START_STRATEGY) VALUES(1,'请假流程',1,'通用请假流程',1,null,'vacation','key');

INSERT INTO BPM_PROCESS(ID,NAME,PRIORITY,DESCN,CATEGORY_ID,PROCESS_DEFINITION_ID,PROCESS_DEFINITION_KEY,START_STRATEGY) VALUES(2,'发文路程',2,'通用发文流程',1,null,'publish','key');

