

-------------------------------------------------------------------------------
--  BOOK BORROW
-------------------------------------------------------------------------------
CREATE TABLE BOOK_BORROW(
        ID BIGINT NOT NULL,
	USER_ID VARCHAR(50),
	BORROW_TIME DATETIME,
	BORROW_OPERATOR VARCHAR(64),
	RETURN_TIME DATETIME,
	RETURN_OPERATOR VARCHAR(64),
	EXPIRE_DATE DATETIME,
	RENEW VARCHAR(50),
	STATUS VARCHAR(50),
	DESCRIPTION VARCHAR(200),
	INFO_ID BIGINT,
	CONSTRAINT PK_BOOK_BORROW PRIMARY KEY(ID),
        CONSTRAINT FK_BOOK_BORROW_INFO FOREIGN KEY(INFO_ID) REFERENCES BOOK_INFO(ID)
) ENGINE=INNODB CHARSET=UTF8;

