package com.mossle.scope.domain;

// Generated by Hibernate Tools
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ScopeGlobal .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "SCOPE_GLOBAL")
public class ScopeGlobal implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private String name;

    /** null. */
    private String reference;

    /** . */
    private Set<ScopeLocal> scopeLocals = new HashSet<ScopeLocal>(0);

    public ScopeGlobal() {
    }

    public ScopeGlobal(String name, String reference,
            Set<ScopeLocal> scopeLocals) {
        this.name = name;
        this.reference = reference;
        this.scopeLocals = scopeLocals;
    }

    /** @return null. */
    @Id
    @GeneratedValue
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @Column(name = "NAME", length = 50)
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            null.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** @return null. */
    @Column(name = "REFERENCE", length = 50)
    public String getReference() {
        return this.reference;
    }

    /**
     * @param reference
     *            null.
     */
    public void setReference(String reference) {
        this.reference = reference;
    }

    /** @return . */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "scopeGlobal")
    public Set<ScopeLocal> getScopeLocals() {
        return this.scopeLocals;
    }

    /**
     * @param scopeLocals
     *            .
     */
    public void setScopeLocals(Set<ScopeLocal> scopeLocals) {
        this.scopeLocals = scopeLocals;
    }
}
