
INSERT INTO PLM_CATEGORY(ID,NAME,PRIORITY) VALUES(1,'通用工具',1);
INSERT INTO PLM_CATEGORY(ID,NAME,PRIORITY) VALUES(2,'系统工具',2);
INSERT INTO PLM_CATEGORY(ID,NAME,PRIORITY) VALUES(3,'基础组件',3);
INSERT INTO PLM_CATEGORY(ID,NAME,PRIORITY) VALUES(4,'业务模块',4);
INSERT INTO PLM_CATEGORY(ID,NAME,PRIORITY) VALUES(5,'内容管理',5);
INSERT INTO PLM_CATEGORY(ID,NAME,PRIORITY) VALUES(99,'孵化器',99);



