

INSERT INTO PARTY_STRUCT_TYPE(ID,TYPE,NAME,PRIORITY,DISPLAY,TENANT_ID) VALUES(2,'manage','管理关系',200,'false','1');
INSERT INTO PARTY_STRUCT_TYPE(ID,TYPE,NAME,PRIORITY,DISPLAY,TENANT_ID) VALUES(3,'superiour','上下级',300,'false','1');
INSERT INTO PARTY_STRUCT_TYPE(ID,TYPE,NAME,PRIORITY,DISPLAY,TENANT_ID) VALUES(4,'position','岗位关系',400,'false','1');
INSERT INTO PARTY_STRUCT_TYPE(ID,TYPE,NAME,PRIORITY,DISPLAY,TENANT_ID) VALUES(5,'user-position','岗位人员',500,'false','1');
INSERT INTO PARTY_STRUCT_TYPE(ID,TYPE,NAME,PRIORITY,DISPLAY,TENANT_ID) VALUES(6,'department-position','部门岗位',600,'false','1');
INSERT INTO PARTY_STRUCT_TYPE(ID,TYPE,NAME,PRIORITY,DISPLAY,TENANT_ID) VALUES(7,'role','角色',700,'false','1');
INSERT INTO PARTY_STRUCT_TYPE(ID,TYPE,NAME,PRIORITY,DISPLAY,TENANT_ID) VALUES(8,'group','群组',800,'false','1');

UPDATE PARTY_STRUCT_TYPE SET TYPE='struct',DISPLAY='true' WHERE ID=1;

DELETE FROM PARTY_STRUCT_RULE WHERE ID=10;
DELETE FROM PARTY_STRUCT_RULE WHERE ID=11;
DELETE FROM PARTY_STRUCT_RULE WHERE ID=12;
DELETE FROM PARTY_STRUCT_RULE WHERE ID=14;

DELETE FROM PARTY_STRUCT WHERE ID=101;
DELETE FROM PARTY_STRUCT WHERE ID=102;
DELETE FROM PARTY_STRUCT WHERE ID=103;
DELETE FROM PARTY_STRUCT WHERE ID=104;

-- mossle -> John
INSERT INTO PARTY_STRUCT(ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,PRIORITY,STRUCT_TYPE_ID,TENANT_ID) VALUES(401,1,12,1,1,'1');
-- 研发部 -> King
INSERT INTO PARTY_STRUCT(ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,PRIORITY,STRUCT_TYPE_ID,TENANT_ID) VALUES(402,5,11,1,1,'1');
-- John -> 总经理
INSERT INTO PARTY_STRUCT(ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,PRIORITY,STRUCT_TYPE_ID,TENANT_ID) VALUES(403,12,15,1,5,'1');
-- King -> 经理
INSERT INTO PARTY_STRUCT(ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,PRIORITY,STRUCT_TYPE_ID,TENANT_ID) VALUES(404,11,16,1,5,'1');
-- mossle -> 总经理
INSERT INTO PARTY_STRUCT(ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,PRIORITY,STRUCT_TYPE_ID,TENANT_ID) VALUES(405,1,15,1,2,'1');
-- 研发部 -> 经理
INSERT INTO PARTY_STRUCT(ID,PARENT_ENTITY_ID,CHILD_ENTITY_ID,PRIORITY,STRUCT_TYPE_ID,TENANT_ID) VALUES(406,5,16,1,2,'1');

