

-------------------------------------------------------------------------------
--  task def operation
-------------------------------------------------------------------------------
CREATE TABLE TASK_DEF_OPERATION(
	ID BIGINT NOT NULL,
	VALUE VARCHAR(200),
	TYPE VARCHAR(50),
	STATUS VARCHAR(50),
	PRIORITY INT,
	BASE_ID BIGINT,
        CONSTRAINT PK_TASK_DEF_OPERATION PRIMARY KEY(ID),
        CONSTRAINT FK_TASK_DEF_OPERATION_BASE FOREIGN KEY(BASE_ID) REFERENCES TASK_DEF_BASE(ID)
);

COMMENT ON TABLE TASK_DEF_OPERATION IS '任务定义操作';
COMMENT ON COLUMN TASK_DEF_OPERATION.ID IS '主键';
COMMENT ON COLUMN TASK_DEF_OPERATION.VALUE IS '值';
COMMENT ON COLUMN TASK_DEF_OPERATION.TYPE IS '类型';
COMMENT ON COLUMN TASK_DEF_OPERATION.STATUS IS '状态';
COMMENT ON COLUMN TASK_DEF_OPERATION.PRIORITY IS '排序';
COMMENT ON COLUMN TASK_DEF_OPERATION.BASE_ID IS '外键，任务定义';


