

alter table TASK_INFO add column ATTR1 varchar(100);
alter table TASK_INFO add column ATTR2 varchar(100);
alter table TASK_INFO add column ATTR3 varchar(100);
alter table TASK_INFO add column ATTR4 varchar(100);
alter table TASK_INFO add column ATTR5 varchar(100);
alter table TASK_INFO add column PROCESS_BUSINESS_KEY VARCHAR(200);
ALTER TABLE TASK_INFO ALTER COLUMN CATALOG RENAME TO CATEGORY;

COMMENT ON COLUMN TASK_INFO.ATTR1 IS '扩展字段1';
COMMENT ON COLUMN TASK_INFO.ATTR2 IS '扩展字段2';
COMMENT ON COLUMN TASK_INFO.ATTR3 IS '扩展字段3';
COMMENT ON COLUMN TASK_INFO.ATTR4 IS '扩展字段4';
COMMENT ON COLUMN TASK_INFO.ATTR5 IS '扩展字段5';
COMMENT ON COLUMN TASK_INFO.PROCESS_BUSINESS_KEY IS '流程业务标识';

