

ALTER TABLE TASK_DEF_BASE ADD COLUMN PROCESS_DEFINITION_KEY VARCHAR(100);
COMMENT ON COLUMN TASK_DEF_BASE.PROCESS_DEFINITION_KEY IS '流程标识';

ALTER TABLE TASK_DEF_BASE ADD COLUMN PROCESS_DEFINITION_VERSION INT;
COMMENT ON COLUMN TASK_DEF_BASE.PROCESS_DEFINITION_VERSION IS '流程版本';

