

ALTER TABLE ASSET_INFO ADD COLUMN CATEGORY_ID BIGINT;
ALTER TABLE ASSET_INFO ADD COLUMN SUB_CATEGORY_ID BIGINT;
ALTER TABLE ASSET_INFO ADD COLUMN MODEL VARCHAR(50);
ALTER TABLE ASSET_INFO ADD COLUMN PRICE FLOAT;
ALTER TABLE ASSET_INFO ADD COLUMN BUY_DATE DATE;
ALTER TABLE ASSET_INFO ADD COLUMN STATUS VARCHAR(50);
ALTER TABLE ASSET_INFO ADD COLUMN USER_ID VARCHAR(64);

ALTER TABLE ASSET_INFO ADD CONSTRAINT FK_ASSET_INFO_CATEGORY FOREIGN KEY(CATEGORY_ID) REFERENCES ASSET_CATEGORY(ID);
ALTER TABLE ASSET_INFO ADD CONSTRAINT FK_ASSET_INFO_SUB FOREIGN KEY(SUB_CATEGORY_ID) REFERENCES ASSET_CATEGORY(ID);

