

INSERT INTO PORTAL_WIDGET(ID,NAME,URL) VALUES(7,'地图','/widgets/map.html');
INSERT INTO PORTAL_WIDGET(ID,NAME,URL) VALUES(8,'时钟','/widgets/clock.html');
INSERT INTO PORTAL_WIDGET(ID,NAME,URL) VALUES(9,'私信','/rs/msg/widget/msg');
INSERT INTO PORTAL_WIDGET(ID,NAME,URL) VALUES(10,'Android','/widgets/android.html');

INSERT INTO PORTAL_ITEM(ID,NAME,COLUMN_INDEX,ROW_INDEX,INFO_ID,WIDGET_ID) VALUES(7,'Android',1,3,1,10);
INSERT INTO PORTAL_ITEM(ID,NAME,COLUMN_INDEX,ROW_INDEX,INFO_ID,WIDGET_ID) VALUES(8,'私信',2,3,1,9);

