

INSERT INTO PORTAL_WIDGET(ID,NAME,URL) VALUES(11,'导航','/cdn/navigation.html');
INSERT INTO PORTAL_WIDGET(ID,NAME,URL) VALUES(12,'日程','/cdn/calendar.html');
INSERT INTO PORTAL_WIDGET(ID,NAME,URL) VALUES(13,'任务','/pim/portal/tasks.do');

INSERT INTO PORTAL_ITEM(ID,NAME,COLUMN_INDEX,ROW_INDEX,INFO_ID,WIDGET_ID) VALUES(9,'导航',3,3,1,11);
INSERT INTO PORTAL_ITEM(ID,NAME,COLUMN_INDEX,ROW_INDEX,INFO_ID,WIDGET_ID) VALUES(10,'日程',1,4,1,12);
INSERT INTO PORTAL_ITEM(ID,NAME,COLUMN_INDEX,ROW_INDEX,INFO_ID,WIDGET_ID) VALUES(11,'任务',2,4,1,13);


UPDATE PORTAL_WIDGET SET URL='/cdn/tools.html' WHERE ID=5;
UPDATE PORTAL_WIDGET SET URL='/cdn/weather.html' WHERE ID=6;
UPDATE PORTAL_WIDGET SET URL='/cdn/map.html' WHERE ID=7;
UPDATE PORTAL_WIDGET SET URL='/cdn/clock.html' WHERE ID=8;
UPDATE PORTAL_WIDGET SET URL='/cdn/android.html' WHERE ID=10;

UPDATE PORTAL_WIDGET SET URL='/humantask/portal/personalTasks.do' WHERE ID=1;
UPDATE PORTAL_WIDGET SET URL='/bpm/portal/runningProcesses.do' WHERE ID=2;
UPDATE PORTAL_WIDGET SET URL='/bpm/portal/processes.do' WHERE ID=3;
UPDATE PORTAL_WIDGET SET URL='/cms/portal/articles.do' WHERE ID=4;
UPDATE PORTAL_WIDGET SET URL='/msg/portal/msg.do' WHERE ID=9;


