
CREATE TABLE GROUP_RELATION(
	ID BIGINT NOT NULL,
	PARENT_ID BIGINT,
	CHILD_ID BIGINT,
	TENANT_ID VARCHAR(64),
        CONSTRAINT PK_GROUP_RELATION PRIMARY KEY(ID),
        CONSTRAINT FK_GROUP_RELATION_PARENT FOREIGN KEY(PARENT_ID) REFERENCES GROUP_INFO(ID),
        CONSTRAINT FK_GROUP_RELATION_CHILD FOREIGN KEY(CHILD_ID) REFERENCES GROUP_INFO(ID)
);
