

ALTER TABLE ACCOUNT_INFO ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE ACCOUNT_CREDENTIAL ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE PERSON_INFO ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE ACCOUNT_AVATAR ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE ACCOUNT_ONLINE ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE ACCOUNT_LOCK_INFO ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE ACCOUNT_LOCK_LOG ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE ACCOUNT_LOG ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE ACCOUNT_HISTORY_CREDENTIAL ADD COLUMN TENANT_ID VARCHAR(64);


COMMENT ON COLUMN ACCOUNT_INFO.TENANT_ID IS '租户';
COMMENT ON COLUMN ACCOUNT_CREDENTIAL.TENANT_ID IS '租户';
COMMENT ON COLUMN PERSON_INFO.TENANT_ID IS '租户';
COMMENT ON COLUMN ACCOUNT_AVATAR.TENANT_ID IS '租户';
COMMENT ON COLUMN ACCOUNT_ONLINE.TENANT_ID IS '租户';
COMMENT ON COLUMN ACCOUNT_LOCK_INFO.TENANT_ID IS '租户';
COMMENT ON COLUMN ACCOUNT_LOCK_LOG.TENANT_ID IS '租户';
COMMENT ON COLUMN ACCOUNT_LOG.TENANT_ID IS '租户';
COMMENT ON COLUMN ACCOUNT_HISTORY_CREDENTIAL.TENANT_ID IS '租户';

