package com.mossle.customer.persistence.domain;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerInfo .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "CUSTOMER_INFO")
public class CustomerInfo implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private String name;

    /** null. */
    private Date createTime;

    /** null. */
    private String status;

    /** null. */
    private String type;

    /** null. */
    private String address;

    /** null. */
    private String contact;

    /** null. */
    private String company;

    /** null. */
    private String description;

    /** null. */
    private String userId;

    /** null. */
    private String tenantId;

    public CustomerInfo() {
    }

    public CustomerInfo(String name, Date createTime, String status,
            String type, String address, String contact, String company,
            String description, String userId, String tenantId) {
        this.name = name;
        this.createTime = createTime;
        this.status = status;
        this.type = type;
        this.address = address;
        this.contact = contact;
        this.company = company;
        this.description = description;
        this.userId = userId;
        this.tenantId = tenantId;
    }

    /** @return null. */
    @Id
    @GeneratedValue
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @Column(name = "NAME", length = 200)
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            null.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** @return null. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATE_TIME", length = 26)
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * @param createTime
     *            null.
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /** @return null. */
    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return this.status;
    }

    /**
     * @param status
     *            null.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /** @return null. */
    @Column(name = "TYPE", length = 50)
    public String getType() {
        return this.type;
    }

    /**
     * @param type
     *            null.
     */
    public void setType(String type) {
        this.type = type;
    }

    /** @return null. */
    @Column(name = "ADDRESS", length = 200)
    public String getAddress() {
        return this.address;
    }

    /**
     * @param address
     *            null.
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /** @return null. */
    @Column(name = "CONTACT", length = 100)
    public String getContact() {
        return this.contact;
    }

    /**
     * @param contact
     *            null.
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /** @return null. */
    @Column(name = "COMPANY", length = 100)
    public String getCompany() {
        return this.company;
    }

    /**
     * @param company
     *            null.
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /** @return null. */
    @Column(name = "DESCRIPTION", length = 65535)
    public String getDescription() {
        return this.description;
    }

    /**
     * @param description
     *            null.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /** @return null. */
    @Column(name = "USER_ID", length = 64)
    public String getUserId() {
        return this.userId;
    }

    /**
     * @param userId
     *            null.
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /** @return null. */
    @Column(name = "TENANT_ID", length = 64)
    public String getTenantId() {
        return this.tenantId;
    }

    /**
     * @param tenantId
     *            null.
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId;
    }
}
