

ALTER TABLE ORG_COMPANY CHANGE SCOPE_ID TENANT_ID VARCHAR(200);
ALTER TABLE ORG_DEPARTMENT CHANGE SCOPE_ID TENANT_ID VARCHAR(200);
ALTER TABLE JOB_GRADE CHANGE SCOPE_ID TENANT_ID VARCHAR(200);
ALTER TABLE JOB_LEVEL CHANGE SCOPE_ID TENANT_ID VARCHAR(200);
ALTER TABLE JOB_TYPE CHANGE SCOPE_ID TENANT_ID VARCHAR(200);
ALTER TABLE JOB_TITLE CHANGE SCOPE_ID TENANT_ID VARCHAR(200);
ALTER TABLE JOB_INFO CHANGE SCOPE_ID TENANT_ID VARCHAR(200);
ALTER TABLE JOB_USER CHANGE SCOPE_ID TENANT_ID VARCHAR(200);

