

ALTER TABLE TICKET_GROUP ADD COLUMN CODE VARCHAR(50);
ALTER TABLE TICKET_GROUP ADD COLUMN PRIORITY INT;

COMMENT ON COLUMN TICKET_GROUP.CODE IS '编码';
COMMENT ON COLUMN TICKET_GROUP.PRIORITY IS '优先级';

