

ALTER TABLE TICKET_INFO ADD COLUMN SURVEY VARCHAR(50);
ALTER TABLE TICKET_INFO ADD COLUMN SURVEY_MESSAGE VARCHAR(200);

COMMENT ON COLUMN TICKET_INFO.SURVEY IS '是否问卷调研';
COMMENT ON COLUMN TICKET_INFO.SURVEY_MESSAGE IS '问卷信息';

