

-------------------------------------------------------------------------------
--  task def base
-------------------------------------------------------------------------------
CREATE TABLE TASK_DEF_BASE(
	ID BIGINT NOT NULL,
	CODE VARCHAR(100),
	NAME VARCHAR(200),
	PROCESS_DEFINITION_ID VARCHAR(200),
	FORM_KEY VARCHAR(200),
	FORM_TYPE VARCHAR(50),
	COUNTERSIGN_TYPE VARCHAR(50),
	COUNTERSIGN_USER VARCHAR(200),
	COUNTERSIGN_STRATEGY VARCHAR(50),
	COUNTERSIGN_RATE INT,
	ASSIGN_STRATEGY VARCHAR(100),
        CONSTRAINT PK_TASK_DEF_BASE PRIMARY KEY(ID)
);

COMMENT ON TABLE TASK_DEF_BASE IS '任务定义';
COMMENT ON COLUMN TASK_DEF_BASE.ID IS '主键';
COMMENT ON COLUMN TASK_DEF_BASE.CODE IS '主键';
COMMENT ON COLUMN TASK_DEF_BASE.NAME IS '名称';
COMMENT ON COLUMN TASK_DEF_BASE.PROCESS_DEFINITION_ID IS '流程定义ID';
COMMENT ON COLUMN TASK_DEF_BASE.FORM_KEY IS '表单编号';
COMMENT ON COLUMN TASK_DEF_BASE.FORM_TYPE IS '表单类型';
COMMENT ON COLUMN TASK_DEF_BASE.COUNTERSIGN_TYPE IS '会签类型';
COMMENT ON COLUMN TASK_DEF_BASE.COUNTERSIGN_USER IS '会签用户';
COMMENT ON COLUMN TASK_DEF_BASE.COUNTERSIGN_STRATEGY IS '会签策略';
COMMENT ON COLUMN TASK_DEF_BASE.COUNTERSIGN_RATE IS '会签通过率';
COMMENT ON COLUMN TASK_DEF_BASE.ASSIGN_STRATEGY IS '分配策略';


