

ALTER TABLE TASK_INFO ADD COLUMN PROCESS_STARTER VARCHAR(64);
COMMENT ON COLUMN TASK_INFO.PROCESS_STARTER IS '关联的流程发起人';

ALTER TABLE TASK_INFO ADD COLUMN CATALOG VARCHAR(100);
COMMENT ON COLUMN TASK_INFO.CATALOG IS '分类';

ALTER TABLE TASK_INFO ADD COLUMN ACTION VARCHAR(200);
COMMENT ON COLUMN TASK_INFO.ACTION IS '操作';

ALTER TABLE TASK_INFO ADD COLUMN COMMENT VARCHAR(200);
COMMENT ON COLUMN TASK_INFO.COMMENT IS '意见';

ALTER TABLE TASK_INFO ADD COLUMN MESSAGE VARCHAR(200);
COMMENT ON COLUMN TASK_INFO.MESSAGE IS '消息';

