
CREATE TABLE BPM_CATEGORY(
	ID BIGINT NOT NULL,
	NAME VARCHAR(200),
	PRIORITY INTEGER,
        CONSTRAINT PK_BPM_CATEGORY PRIMARY KEY(ID)
);

COMMENT ON TABLE BPM_CATEGORY IS '流程分类';
COMMENT ON COLUMN BPM_CATEGORY.ID IS '主键';
COMMENT ON COLUMN BPM_CATEGORY.NAME IS '名称';
COMMENT ON COLUMN BPM_CATEGORY.PRIORITY IS '排序';

