
CREATE TABLE BPM_CONF_OPERATION(
	ID BIGINT NOT NULL,
	VALUE VARCHAR(200),
	PRIORITY INT,
	NODE_ID BIGINT,
        CONSTRAINT PK_BPM_CONF_OPERATION PRIMARY KEY(ID),
        CONSTRAINT FK_BPM_CONF_OPERATION_NODE FOREIGN KEY(NODE_ID) REFERENCES BPM_CONF_NODE(ID)
);

COMMENT ON TABLE BPM_CONF_OPERATION IS '配置操作';
COMMENT ON COLUMN BPM_CONF_OPERATION.ID IS '主键';
COMMENT ON COLUMN BPM_CONF_OPERATION.VALUE IS '值';
COMMENT ON COLUMN BPM_CONF_OPERATION.PRIORITY IS '排序';
COMMENT ON COLUMN BPM_CONF_OPERATION.NODE_ID IS '外键，配置节点';

