
CREATE TABLE BPM_CONF_BASE(
	ID BIGINT NOT NULL,
	PROCESS_DEFINITION_ID VARCHAR(200),
	PROCESS_DEFINITION_KEY VARCHAR(200),
	PROCESS_DEFINITION_VERSION INT,
        CONSTRAINT PK_BPM_CONF_BASE PRIMARY KEY(ID)
);

COMMENT ON TABLE BPM_CONF_BASE IS '流程配置';
COMMENT ON COLUMN BPM_CONF_BASE.ID IS '主键';
COMMENT ON COLUMN BPM_CONF_BASE.PROCESS_DEFINITION_ID IS '流程定义ID';
COMMENT ON COLUMN BPM_CONF_BASE.PROCESS_DEFINITION_KEY IS '流程定义KEY';
COMMENT ON COLUMN BPM_CONF_BASE.PROCESS_DEFINITION_VERSION IS '流程定义版本';

