
CREATE TABLE BPM_CONF_USER(
	ID BIGINT NOT NULL,
	VALUE VARCHAR(200),
	TYPE INT,
	STATUS INT,
	PRIORITY INT,
	NODE_ID BIGINT,
        CONSTRAINT PK_BPM_CONF_USER PRIMARY KEY(ID),
        CONSTRAINT FK_BPM_CONF_USER_NODE FOREIGN KEY(NODE_ID) REFERENCES BPM_CONF_NODE(ID)
);

COMMENT ON TABLE BPM_CONF_USER IS '配置用户';
COMMENT ON COLUMN BPM_CONF_USER.ID IS '主键';
COMMENT ON COLUMN BPM_CONF_USER.VALUE IS '值';
COMMENT ON COLUMN BPM_CONF_USER.TYPE IS '分类';
COMMENT ON COLUMN BPM_CONF_USER.STATUS IS '状态';
COMMENT ON COLUMN BPM_CONF_USER.PRIORITY IS '排序';
COMMENT ON COLUMN BPM_CONF_USER.NODE_ID IS '外键，配置节点';

