
CREATE TABLE BPM_CONF_LISTENER(
	ID BIGINT NOT NULL,
	VALUE VARCHAR(200),
	TYPE INT,
	STATUS INT,
	PRIORITY INT,
	NODE_ID BIGINT,
        CONSTRAINT PK_BPM_CONF_LISTENER PRIMARY KEY(ID),
        CONSTRAINT FK_BPM_CONF_LISTENER_NODE FOREIGN KEY(NODE_ID) REFERENCES BPM_CONF_NODE(ID)
);

COMMENT ON TABLE BPM_CONF_LISTENER IS '配置回调';
COMMENT ON COLUMN BPM_CONF_LISTENER.ID IS '主键';
COMMENT ON COLUMN BPM_CONF_LISTENER.VALUE IS '值';
COMMENT ON COLUMN BPM_CONF_LISTENER.TYPE IS '分类';
COMMENT ON COLUMN BPM_CONF_LISTENER.STATUS IS '状态';
COMMENT ON COLUMN BPM_CONF_LISTENER.PRIORITY IS '排序';
COMMENT ON COLUMN BPM_CONF_LISTENER.NODE_ID IS '外键，配置节点';

