
ALTER TABLE BPM_PROCESS ADD COLUMN CODE VARCHAR(64);
ALTER TABLE BPM_PROCESS ADD COLUMN CONF_BASE_ID BIGINT;

ALTER TABLE BPM_PROCESS ADD CONSTRAINT FK_BPM_PROCESS_CONF_BASE FOREIGN KEY(CONF_BASE_ID) REFERENCES BPM_CONF_BASE(ID);

ALTER TABLE BPM_PROCESS DROP COLUMN PROCESS_DEFINITION_KEY;
ALTER TABLE BPM_PROCESS DROP COLUMN PROCESS_DEFINITION_VERSION;

COMMENT ON COLUMN BPM_PROCESS.CODE IS '编码';
COMMENT ON COLUMN BPM_PROCESS.CONF_BASE_ID IS '外键，流程配置';
