

ALTER TABLE BPM_CONF_NOTICE ADD COLUMN TEMPLATE_CODE VARCHAR(200);
ALTER TABLE BPM_CONF_NOTICE ADD COLUMN NOTIFICATION_TYPE VARCHAR(200);

COMMENT ON COLUMN BPM_CONF_NOTICE.TEMPLATE_CODE IS '模板编码';
COMMENT ON COLUMN BPM_CONF_NOTICE.NOTIFICATION_TYPE IS '提醒类型';
