

ALTER TABLE BPM_CATEGORY ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE BPM_PROCESS ADD COLUMN TENANT_ID VARCHAR(64);

COMMENT ON COLUMN BPM_CATEGORY.TENANT_ID IS '租户';
COMMENT ON COLUMN BPM_PROCESS.TENANT_ID IS '租户';


