

ALTER TABLE BPM_CATEGORY ADD COLUMN CODE VARCHAR(200);
ALTER TABLE BPM_CATEGORY ADD COLUMN STATUS VARCHAR(50);
ALTER TABLE BPM_CATEGORY ADD COLUMN PARENT_ID BIGINT;
ALTER TABLE BPM_CATEGORY ADD CONSTRAINT FK_BPM_CATEGORY_PARENT FOREIGN KEY (PARENT_ID) REFERENCES BPM_CATEGORY(ID);

