

-------------------------------------------------------------------------------
--  whitelist type
-------------------------------------------------------------------------------
CREATE TABLE WHITELIST_TYPE(
        ID BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
	NAME VARCHAR(50),
	CODE VARCHAR(50),
        CONSTRAINT PK_WHITELIST_TYPE PRIMARY KEY(ID)
);

