

ALTER TABLE DICT_TYPE ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE DICT_SCHEMA ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE DICT_INFO ADD COLUMN TENANT_ID VARCHAR(64);
ALTER TABLE DICT_DATA ADD COLUMN TENANT_ID VARCHAR(64);




