package com.mossle.acl.domain;

// Generated by Hibernate Tools
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AclEntry .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "ACL_ENTRY")
public class AclEntry implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private AclObjectIdentity aclObjectIdentity;

    /** null. */
    private Integer aceOrder;

    /** null. */
    private Integer granting;

    /** null. */
    private Integer auditSuccess;

    /** null. */
    private Integer auditFailure;

    /** null. */
    private Integer mask;

    /** null. */
    private Long sidId;

    /** null. */
    private Long globalId;

    /** null. */
    private Long localId;

    /** null. */
    private Date startTime;

    /** null. */
    private Date endTime;

    public AclEntry() {
    }

    public AclEntry(AclObjectIdentity aclObjectIdentity, Integer aceOrder,
            Integer granting, Integer auditSuccess, Integer auditFailure,
            Integer mask, Long sidId, Long globalId, Long localId,
            Date startTime, Date endTime) {
        this.aclObjectIdentity = aclObjectIdentity;
        this.aceOrder = aceOrder;
        this.granting = granting;
        this.auditSuccess = auditSuccess;
        this.auditFailure = auditFailure;
        this.mask = mask;
        this.sidId = sidId;
        this.globalId = globalId;
        this.localId = localId;
        this.startTime = startTime;
        this.endTime = endTime;
    }

    /** @return null. */
    @Id
    @GeneratedValue
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "OBJECT_IDENTITY_ID")
    public AclObjectIdentity getAclObjectIdentity() {
        return this.aclObjectIdentity;
    }

    /**
     * @param aclObjectIdentity
     *            null.
     */
    public void setAclObjectIdentity(AclObjectIdentity aclObjectIdentity) {
        this.aclObjectIdentity = aclObjectIdentity;
    }

    /** @return null. */
    @Column(name = "ACE_ORDER")
    public Integer getAceOrder() {
        return this.aceOrder;
    }

    /**
     * @param aceOrder
     *            null.
     */
    public void setAceOrder(Integer aceOrder) {
        this.aceOrder = aceOrder;
    }

    /** @return null. */
    @Column(name = "GRANTING")
    public Integer getGranting() {
        return this.granting;
    }

    /**
     * @param granting
     *            null.
     */
    public void setGranting(Integer granting) {
        this.granting = granting;
    }

    /** @return null. */
    @Column(name = "AUDIT_SUCCESS")
    public Integer getAuditSuccess() {
        return this.auditSuccess;
    }

    /**
     * @param auditSuccess
     *            null.
     */
    public void setAuditSuccess(Integer auditSuccess) {
        this.auditSuccess = auditSuccess;
    }

    /** @return null. */
    @Column(name = "AUDIT_FAILURE")
    public Integer getAuditFailure() {
        return this.auditFailure;
    }

    /**
     * @param auditFailure
     *            null.
     */
    public void setAuditFailure(Integer auditFailure) {
        this.auditFailure = auditFailure;
    }

    /** @return null. */
    @Column(name = "MASK")
    public Integer getMask() {
        return this.mask;
    }

    /**
     * @param mask
     *            null.
     */
    public void setMask(Integer mask) {
        this.mask = mask;
    }

    /** @return null. */
    @Column(name = "SID_ID")
    public Long getSidId() {
        return this.sidId;
    }

    /**
     * @param sidId
     *            null.
     */
    public void setSidId(Long sidId) {
        this.sidId = sidId;
    }

    /** @return null. */
    @Column(name = "GLOBAL_ID")
    public Long getGlobalId() {
        return this.globalId;
    }

    /**
     * @param globalId
     *            null.
     */
    public void setGlobalId(Long globalId) {
        this.globalId = globalId;
    }

    /** @return null. */
    @Column(name = "LOCAL_ID")
    public Long getLocalId() {
        return this.localId;
    }

    /**
     * @param localId
     *            null.
     */
    public void setLocalId(Long localId) {
        this.localId = localId;
    }

    /** @return null. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "START_TIME", length = 26)
    public Date getStartTime() {
        return this.startTime;
    }

    /**
     * @param startTime
     *            null.
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /** @return null. */
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "END_TIME", length = 26)
    public Date getEndTime() {
        return this.endTime;
    }

    /**
     * @param endTime
     *            null.
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}
