

-------------------------------------------------------------------------------
--  vehicle driver
-------------------------------------------------------------------------------
CREATE TABLE VEHICLE_DRIVER(
        ID BIGINT NOT NULL,
	NAME VARCHAR(50),
	GENDER VARCHAR(50),
	BIRTHDAY DATE,
	CODE VARCHAR(50),
	LICENSE_DATE DATE,
	EXPIRE_DATE DATE,
	YEAR INTEGER,
	TYPE VARCHAR(50),
	MOBILE VARCHAR(50),
	LOCATION VARCHAR(200),
	ANNUAL_INSPECTION varchar(200),
	STATUS INTEGER,
	DESCRIPTION VARCHAR(200),
	TENANT_ID VARCHAR(64),
        CONSTRAINT PK_VEHICLE_DRIVER PRIMARY KEY(ID)
);

COMMENT ON TABLE VEHICLE_DRIVER IS '车辆信息';
COMMENT ON COLUMN VEHICLE_DRIVER.ID IS '主键';
COMMENT ON COLUMN VEHICLE_DRIVER.NAME IS '姓名';
COMMENT ON COLUMN VEHICLE_DRIVER.GENDER IS '性别';
COMMENT ON COLUMN VEHICLE_DRIVER.BIRTHDAY IS '生日';
COMMENT ON COLUMN VEHICLE_DRIVER.CODE IS '驾驶证号码';
COMMENT ON COLUMN VEHICLE_DRIVER.LICENSE_DATE IS '领证时间';
COMMENT ON COLUMN VEHICLE_DRIVER.EXPIRE_DATE IS '驾驶证到期时间';
COMMENT ON COLUMN VEHICLE_DRIVER.YEAR IS '驾龄';
COMMENT ON COLUMN VEHICLE_DRIVER.TYPE IS '准驾车型';
COMMENT ON COLUMN VEHICLE_DRIVER.MOBILE IS '电话';
COMMENT ON COLUMN VEHICLE_DRIVER.LOCATION IS '地址';
COMMENT ON COLUMN VEHICLE_DRIVER.ANNUAL_INSPECTION IS '年检记录';
COMMENT ON COLUMN VEHICLE_DRIVER.STATUS IS '状态';
COMMENT ON COLUMN VEHICLE_DRIVER.DESCRIPTION IS '备注';
COMMENT ON COLUMN VEHICLE_DRIVER.TENANT_ID IS '租户';
