

-------------------------------------------------------------------------------
--  store attach
-------------------------------------------------------------------------------
CREATE TABLE STORE_ATTACH(
    ID BIGINT NOT NULL,
    CATALOG VARCHAR(200),
    BUSINESS_KEY VARCHAR(200),
    STATUS VARCHAR(50),
    CREATE_TIME TIMESTAMP,
	CONFIRM_TIME TIMESTAMP,
	DESCRIPTION VARCHAR(200),
	ATTR1 VARCHAR(200),
	ATTR2 VARCHAR(200),
	ATTR3 VARCHAR(200),
	ATTR4 VARCHAR(200),
	ATTR5 VARCHAR(200),
	TENANT_ID VARCHAR(50),
	INFO_ID BIGINT,
    CONSTRAINT PK_STORE_ATTACH PRIMARY KEY(ID),
    CONSTRAINT FK_STORE_ATTACH_INFO FOREIGN KEY(INFO_ID) REFERENCES STORE_INFO(ID)
) ENGINE=INNODB CHARSET=UTF8;
