

INSERT INTO BPM_CATEGORY(ID,NAME,PRIORITY) VALUES(1,'常用流程',1);

INSERT INTO BPM_PROCESS(ID,NAME,PRIORITY,DESCN,CATEGORY_ID,USE_TASK_CONF) VALUES(1,'请假流程',1,'通用请假流程',1,0);

INSERT INTO BPM_PROCESS(ID,NAME,PRIORITY,DESCN,CATEGORY_ID,USE_TASK_CONF) VALUES(2,'发文流程',2,'通用发文流程',1,0);

INSERT INTO BPM_PROCESS(ID,NAME,PRIORITY,DESCN,CATEGORY_ID,USE_TASK_CONF) VALUES(3,'权限审批',3,'权限审批流程',1,1);

INSERT INTO BPM_MAIL_TEMPLATE(ID,NAME,SUBJECT,CONTENT) VALUES(1,'任务到达（任务处理人）','您有新任务需要处理','#{task.assignee}您好，您有新任务需要处理——#{task.name}。');

INSERT INTO BPM_MAIL_TEMPLATE(ID,NAME,SUBJECT,CONTENT) VALUES(2,'任务到达（流程发起人）','您的流程已经到达#{task.name}环节','#{initiator}您好，您的流程已经到达#{task.name}环节');

INSERT INTO BPM_MAIL_TEMPLATE(ID,NAME,SUBJECT,CONTENT) VALUES(3,'任务完成','流程已经完成#{task.name}环节','您好，#{initiator}的流程已经完成#{task.name}环节');

INSERT INTO BPM_MAIL_TEMPLATE(ID,NAME,SUBJECT,CONTENT) VALUES(4,'任务超时提醒','任务即将过期','#{task.assignee}您好，任务#{task.name}已经即将到期');

INSERT INTO BPM_TASK_DEF_NOTICE(ID,TASK_DEFINITION_KEY,TYPE,RECEIVER,TEMPLATE_ID,DUE_DATE,PROCESS_ID) VALUES(1,'taskuser-2',0,'任务接收人',1,NULL,1);

INSERT INTO BPM_TASK_DEF_NOTICE(ID,TASK_DEFINITION_KEY,TYPE,RECEIVER,TEMPLATE_ID,DUE_DATE,PROCESS_ID) VALUES(2,'taskuser-3',0,'流程发起人',2,NULL,1);

INSERT INTO BPM_TASK_DEF_NOTICE(ID,TASK_DEFINITION_KEY,TYPE,RECEIVER,TEMPLATE_ID,DUE_DATE,PROCESS_ID) VALUES(3,'taskuser-6',1,'king',3,NULL,1);

INSERT INTO BPM_TASK_DEF_NOTICE(ID,TASK_DEFINITION_KEY,TYPE,RECEIVER,TEMPLATE_ID,DUE_DATE,PROCESS_ID) VALUES(4,'taskuser-6',2,'任务接收人',4,'P1H',1);

