
CREATE TABLE PARTY_TYPE(
        ID BIGINT NOT NULL,
        NAME VARCHAR(50),
	PERSON INTEGER,
	SCOPE_ID VARCHAR(50),
        CONSTRAINT PK_PARTY_TYPE PRIMARY KEY(ID)
);

COMMENT ON TABLE PARTY_TYPE IS '组织类型';
COMMENT ON COLUMN PARTY_TYPE.ID IS '主键';
COMMENT ON COLUMN PARTY_TYPE.NAME IS '名称';
COMMENT ON COLUMN PARTY_TYPE.SCOPE_ID IS '租户';
