

ALTER TABLE PARTY_TYPE DROP COLUMN PERSON;
ALTER TABLE PARTY_TYPE ADD COLUMN TYPE INT;
ALTER TABLE PARTY_TYPE ADD COLUMN REF VARCHAR(50);

COMMENT ON COLUMN PARTY_TYPE.TYPE IS '类型';
COMMENT ON COLUMN PARTY_TYPE.REF IS '外部引用';

