

-------------------------------------------------------------------------------
--  plm issue
-------------------------------------------------------------------------------
CREATE TABLE PLM_ISSUE(
        ID BIGINT NOT NULL,
	TYPE VARCHAR(50),
	NAME VARCHAR(200),
	CONTENT VARCHAR(65535),
	SEVERITY INT,
	CREATE_TIME DATETIME,
	START_TIME DATETIME,
	COMPLETE_TIME DATETIME,
	REPORTER_ID VARCHAR(64),
	ASSIGNEE_ID VARCHAR(64),
	STATUS VARCHAR(50),
	STEP VARCHAR(50),
	PROJECT_ID BIGINT,
	SPRINT_ID BIGINT,
	CONSTRAINT PK_PLM_ISSUE PRIMARY KEY(ID),
        CONSTRAINT FK_PLM_ISSUE_PROJECT FOREIGN KEY(PROJECT_ID) REFERENCES PLM_PROJECT(ID),
	CONSTRAINT FK_PLM_ISSUE_SPRINT FOREIGN KEY(SPRINT_ID) REFERENCES PLM_SPRINT(ID)
);

