
UPDATE CMS_ARTICLE SET CODE='lemon-1-4-0' WHERE ID=1;
UPDATE CMS_ARTICLE SET CODE='lemon-1-3-1' WHERE ID=2;
UPDATE CMS_ARTICLE SET CODE='lemon-1-3-0' WHERE ID=3;
UPDATE CMS_ARTICLE SET CODE='lemon-1-2-0' WHERE ID=4;
UPDATE CMS_ARTICLE SET CODE='lemon-1-1-0' WHERE ID=5;
UPDATE CMS_ARTICLE SET CODE='lemon-1-0-0' WHERE ID=6;
UPDATE CMS_ARTICLE SET CODE='lemon-0-9-0' WHERE ID=7;
UPDATE CMS_ARTICLE SET CODE='lemon-0-8-0' WHERE ID=8;

