package com.mossle.audit.domain;

// Generated by Hibernate Tools
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AuditExtra .
 * 
 * @author Lingo
 */
@Entity
@Table(name = "AUDIT_EXTRA")
public class AuditExtra implements java.io.Serializable {
    private static final long serialVersionUID = 0L;

    /** null. */
    private Long id;

    /** null. */
    private String name;

    /** null. */
    private String value;

    /** null. */
    private Long auditBaseId;

    public AuditExtra() {
    }

    public AuditExtra(String name, String value, Long auditBaseId) {
        this.name = name;
        this.value = value;
        this.auditBaseId = auditBaseId;
    }

    /** @return null. */
    @Id
    @GeneratedValue
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    /**
     * @param id
     *            null.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /** @return null. */
    @Column(name = "NAME", length = 200)
    public String getName() {
        return this.name;
    }

    /**
     * @param name
     *            null.
     */
    public void setName(String name) {
        this.name = name;
    }

    /** @return null. */
    @Column(name = "VALUE", length = 200)
    public String getValue() {
        return this.value;
    }

    /**
     * @param value
     *            null.
     */
    public void setValue(String value) {
        this.value = value;
    }

    /** @return null. */
    @Column(name = "AUDIT_BASE_ID")
    public Long getAuditBaseId() {
        return this.auditBaseId;
    }

    /**
     * @param auditBaseId
     *            null.
     */
    public void setAuditBaseId(Long auditBaseId) {
        this.auditBaseId = auditBaseId;
    }
}
